// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * order?: string // Order
 * onmq97dGETCHange?: any // onmq97dGETCHange
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * variant?: '4:5' | '1:1' | '4:3' | '3:2' | '16:9' // Variant
 * onYHNSBUU8vChange?: any // onYHNSBUU8vChange
 * videoVisible?: boolean // Video Visible
 * ong_5veJ1v3Change?: any // ong_5veJ1v3Change
 * video?: string // Video
 * onXtcSpZkXRCHange?: any // onXtcSpZkXRCHange
 * click?: Function // Click
}} Props

 */
import { stdin_default } from "./chunks/chunk-DY3YN3KF.js";
import "./chunks/chunk-G23ZMBOH.js";
import { className, css, fonts } from "./chunks/chunk-INR2ZGQA.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:archive-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gzQ41rejWtF34iPFAwpI/FryCRHWczNfwfLvUS0xC/RDzKw6B4w.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var AspectRatioFonts = getFonts(stdin_default);
var AspectRatioControls = getPropertyControls(stdin_default);
var enabledGestures = {
	ROEcLEoWF: {
		hover: true,
	},
};
var serializationHash = "framer-HHEDr";
var variantClassNames = {
	ROEcLEoWF: "framer-v-9d1x2n",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	"1:1": "C75SQeAXS",
	"16:9": "iLGiHRb8_",
	"3:2": "PbPK45whq",
	"4:3": "sip9vn1jk",
	"4:5": "pU1s_A_4A",
};
var getProps = ({
	click,
	height,
	id,
	image,
	order,
	variant1,
	video,
	videoVisible,
	width,
	...props
}) => {
	return {
		...props,
		AW8q261qq: image ?? props.AW8q261qq,
		FDIaKrS12: click ?? props.FDIaKrS12,
		g_5veJ1v3: videoVisible ?? props.g_5veJ1v3 ?? true,
		mq97d_gET: order ?? props.mq97d_gET ?? "01",
		XtcSpZkXR: video ?? props.XtcSpZkXR,
		YHNSbUU8v:
			humanReadableEnumMap[variant1] ??
			variant1 ??
			props.YHNSbUU8v ??
			"pU1s_A_4A",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		mq97d_gET: mq97d_gET2,
		AW8q261qq: AW8q261qq2,
		YHNSbUU8v: YHNSbUU8v2,
		g_5veJ1v3: g_5veJ1v32,
		XtcSpZkXR: XtcSpZkXR2,
		FDIaKrS12: FDIaKrS122,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ROEcLEoWF",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapywv3pi = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (FDIaKrS122) {
			const res = await FDIaKrS122(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-9d1x2n",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ROEcLEoWF"}
						onTap={onTapywv3pi}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"ROEcLEoWF-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-6qfp6x"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"vxaXz7v26"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={mq97d_gET2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									suppressHydrationWarning={true}
									className={"framer-styles-preset-yxd5fr"}
									data-styles-preset={"m15z4oKOs"}
								>
									{"01"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<ComponentViewportProvider
							suppressHydrationWarning={true}
							height={500}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 529.5) - 0 - 592) / 2 + 84 + 8)
							}
						>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-gybez4-container"}
								layoutDependency={layoutDependency}
								layoutId={"stvKY_hPV-container"}
								nodeId={"stvKY_hPV"}
								rendersWithMotion={true}
								scopeId={"RDzKw6B4w"}
								style={{
									filter: "brightness(0.75)",
									WebkitFilter: "brightness(0.75)",
								}}
								variants={{
									"ROEcLEoWF-hover": {
										filter: "brightness(1)",
										WebkitFilter: "brightness(1)",
									},
								}}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									AQYOlE2Ws: XtcSpZkXR2,
									height: "100%",
									id: "stvKY_hPV",
									layoutId: "stvKY_hPV",
									RzspQAp52: toResponsiveImage(AW8q261qq2),
									style: {
										width: "100%",
									},
									variant: matchVariant(YHNSbUU8v2),
									width: "100%",
									wrFqzdxX4: g_5veJ1v32,
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	".framer-HHEDr.framer-rnsphq, .framer-HHEDr .framer-rnsphq { display: block; }",
	".framer-HHEDr.framer-9d1x2n { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 400px; }",
	".framer-HHEDr .framer-6qfp6x { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-HHEDr .framer-gybez4-container { flex: none; height: auto; position: relative; width: 100%; }",
	...css,
];
var FramerRDzKw6B4w = withCSS(Component, css2, "framer-HHEDr");
var stdin_default2 = FramerRDzKw6B4w;
FramerRDzKw6B4w.displayName = "Archive Card";
FramerRDzKw6B4w.defaultProps = {
	height: 529.5,
	width: 400,
};
addPropertyControls(FramerRDzKw6B4w, {
	mq97d_gET: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Order",
		type: ControlType.String,
	},
	onmq97d_gETChange: {
		changes: "mq97d_gET",
		type: ControlType.ChangeHandler,
	},
	AW8q261qq: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	YHNSbUU8v: AspectRatioControls?.["variant"] && {
		...AspectRatioControls["variant"],
		defaultValue: "pU1s_A_4A",
		description: void 0,
		hidden: void 0,
		optional: void 0,
		title: "Variant",
	},
	onYHNSbUU8vChange: {
		changes: "YHNSbUU8v",
		type: ControlType.ChangeHandler,
	},
	g_5veJ1v3: {
		defaultValue: true,
		title: "Video Visible",
		type: ControlType.Boolean,
	},
	ong_5veJ1v3Change: {
		changes: "g_5veJ1v3",
		type: ControlType.ChangeHandler,
	},
	XtcSpZkXR: AspectRatioControls?.["AQYOlE2Ws"] && {
		...AspectRatioControls["AQYOlE2Ws"],
		__defaultAssetReference: "",
		description: void 0,
		hidden: void 0,
		title: "Video",
	},
	onXtcSpZkXRChange: {
		changes: "XtcSpZkXR",
		type: ControlType.ChangeHandler,
	},
	FDIaKrS12: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerRDzKw6B4w,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...AspectRatioFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerRDzKw6B4w.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:archive-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ArchiveCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var archive_card_default = ComponentWithRoot;
export { archive_card_default as default };
