// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * question1?: string // Question 1
 * answer1?: string // Answer 1
 * question2?: string // Question 2
 * answer2?: string // Answer 2
 * question3?: string // Question 3
 * answer3?: string // Answer 3
 * question4?: string // Question 4
 * answer4?: string // Answer 4
 * question5?: string // Question 5
 * answer5?: string // Answer 5
}} Props

 */
import { stdin_default } from "./chunks/chunk-ND2PKRAY.js";
import "./chunks/chunk-YIX4HD6O.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:fa-qs
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zRxkkIu2AjxX5CIvUyV1/WafBhJe2knt5M2Xx4y7A/DXioAL2NL.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/h8ioHyt4BUxuvVCE1Q10/aTM6mEMGlM19JjX8exDe/AvoidLayoutJumping_Prod.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useRef } from "react";
function AvoidLayoutJumping({ direction, style }) {
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const ref = useRef(null);
	const rafId = useRef();
	const vertical = direction === "vertical" || direction === "both";
	const horizontal = direction === "horizontal" || direction === "both";
	useEffect(() => {
		if (isCanvas) return;
		const parent = ref.current?.parentElement?.parentElement;
		if (!parent) return;
		const container = parent.parentElement;
		if (!container) return;
		const updateSize = () => {
			const rect = parent.getBoundingClientRect();
			if (horizontal) {
				container.style.width = `${rect.width}px`;
			}
			if (vertical) {
				container.style.height = `${rect.height}px`;
			}
			rafId.current = requestAnimationFrame(updateSize);
		};
		rafId.current = requestAnimationFrame(updateSize);
		return () => {
			if (rafId.current) {
				cancelAnimationFrame(rafId.current);
			}
			if (container) {
				if (horizontal) {
					container.style.width = "";
				}
				if (vertical) {
					container.style.height = "";
				}
			}
		};
	}, [direction]);
	return (
		<div
			suppressHydrationWarning={true}
			ref={ref}
			style={{
				...style,
			}}
		/>
	);
}
AvoidLayoutJumping.displayName = "Layout Jump Preventer";
addPropertyControls(AvoidLayoutJumping, {
	direction: {
		type: ControlType.Enum,
		defaultValue: "vertical",
		options: ["vertical", "horizontal", "both"],
		optionTitles: ["Vertical", "Horizontal", "Both"],
		displaySegmentedControl: true,
		segmentedControlDirection: "vertical",
		// @ts-ignore
		optionIcons: [
			"direction-vertical",
			"direction-horizontal",
			"direction-all",
		],
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/zRxkkIu2AjxX5CIvUyV1/WafBhJe2knt5M2Xx4y7A/DXioAL2NL.js
var AccordionFonts = getFonts(stdin_default);
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var serializationHash = "framer-rfO63";
var variantClassNames = {
	oowGtn3B_: "framer-v-9kveti",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	answer1,
	answer2,
	answer3,
	answer4,
	answer5,
	height,
	id,
	question1,
	question2,
	question3,
	question4,
	question5,
	width,
	...props
}) => {
	return {
		...props,
		ApkKi7SYs:
			question4 ??
			props.ApkKi7SYs ??
			"How do I add this FAQ component to my project?",
		IdiX4w72s: question3 ?? props.IdiX4w72s ?? "What is this FAQ component?",
		j_EfdrGoD:
			answer2 ??
			props.j_EfdrGoD ??
			"Framer is fully visual with no code needed, but you can still add custom code and components for more control if you're a designer or developer.",
		rV343XnZp:
			answer4 ??
			props.rV343XnZp ??
			"After duplicating, copy and paste the component into your Framer project. Then edit the questions, answers, styles, and animations as needed.",
		svZsCKZ7a: question1 ?? props.svZsCKZ7a ?? "What is Framer?",
		SZGafHI2T:
			answer5 ??
			props.SZGafHI2T ??
			"Yes, absolutely. The component is built using native Framer tools, so you can tweak fonts, colors, spacing, animations, and layout however you like.",
		UV7N3G2yB:
			question2 ??
			props.UV7N3G2yB ??
			"Do I need to know how to code to use Framer?",
		xHGoJVa3_:
			answer1 ??
			props.xHGoJVa3_ ??
			"Framer is a no-code tool for building and publishing responsive websites\u2014perfect for anyone creating modern, high-performance pages without coding.",
		yIgVEHYaT:
			answer3 ??
			props.yIgVEHYaT ??
			"This is a free, responsive FAQ section for Framer. Drop it into any project, customize styles and text, and use it to save time on support or info pages.",
		Yp26WXhzg:
			question5 ??
			props.Yp26WXhzg ??
			"Can I customize the design of this component?",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		svZsCKZ7a,
		xHGoJVa3_,
		UV7N3G2yB,
		j_EfdrGoD,
		IdiX4w72s,
		yIgVEHYaT,
		ApkKi7SYs,
		rV343XnZp,
		Yp26WXhzg,
		SZGafHI2T,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "oowGtn3B_",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(svZsCKZ7a);
	const visible1 = isSet(UV7N3G2yB);
	const visible2 = isSet(IdiX4w72s);
	const visible3 = isSet(ApkKi7SYs);
	const visible4 = isSet(Yp26WXhzg);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-9kveti",
							className,
							classNames,
						)}
						data-framer-name={"All closed"}
						layoutDependency={layoutDependency}
						layoutId={"oowGtn3B_"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						{visible && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={47}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 224) - 0 - 0) / 2 + 0 + 0)
								}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-7un4vn-container"}
									layoutDependency={layoutDependency}
									layoutId={"ZFu7p_Ajb-container"}
									nodeId={"ZFu7p_Ajb"}
									rendersWithMotion={true}
									scopeId={"DXioAL2NL"}
								>
									{_jsx2(stdin_default, {
										suppressHydrationWarning: true,
										DR_6QqGeh: xHGoJVa3_,
										height: "100%",
										id: "ZFu7p_Ajb",
										layoutId: "ZFu7p_Ajb",
										qQefXa5XK: svZsCKZ7a,
										style: {
											width: "100%",
										},
										variant: "WnUthkAAH",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible1 && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={47}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 224) - 0 - 0) / 2 + 0 + 0)
								}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-152r329-container"}
									layoutDependency={layoutDependency}
									layoutId={"eefngLERN-container"}
									nodeId={"eefngLERN"}
									rendersWithMotion={true}
									scopeId={"DXioAL2NL"}
								>
									{_jsx2(stdin_default, {
										suppressHydrationWarning: true,
										DR_6QqGeh: j_EfdrGoD,
										height: "100%",
										id: "eefngLERN",
										layoutId: "eefngLERN",
										qQefXa5XK: UV7N3G2yB,
										style: {
											width: "100%",
										},
										variant: "WnUthkAAH",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible2 && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={47}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 224) - 0 - 0) / 2 + 0 + 0)
								}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-1lz8y3l-container"}
									layoutDependency={layoutDependency}
									layoutId={"xhw3UpK04-container"}
									nodeId={"xhw3UpK04"}
									rendersWithMotion={true}
									scopeId={"DXioAL2NL"}
								>
									{_jsx2(stdin_default, {
										suppressHydrationWarning: true,
										DR_6QqGeh: yIgVEHYaT,
										height: "100%",
										id: "xhw3UpK04",
										layoutId: "xhw3UpK04",
										qQefXa5XK: IdiX4w72s,
										style: {
											width: "100%",
										},
										variant: "WnUthkAAH",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible3 && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={47}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 224) - 0 - 0) / 2 + 0 + 0)
								}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-gaynpv-container"}
									layoutDependency={layoutDependency}
									layoutId={"kWKorojyF-container"}
									nodeId={"kWKorojyF"}
									rendersWithMotion={true}
									scopeId={"DXioAL2NL"}
								>
									{_jsx2(stdin_default, {
										suppressHydrationWarning: true,
										DR_6QqGeh: rV343XnZp,
										height: "100%",
										id: "kWKorojyF",
										layoutId: "kWKorojyF",
										qQefXa5XK: ApkKi7SYs,
										style: {
											width: "100%",
										},
										variant: "WnUthkAAH",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible4 && (
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={47}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 224) - 0 - 0) / 2 + 0 + 0)
								}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-cl8yp3-container"}
									layoutDependency={layoutDependency}
									layoutId={"BzUIEoIOD-container"}
									nodeId={"BzUIEoIOD"}
									rendersWithMotion={true}
									scopeId={"DXioAL2NL"}
								>
									{_jsx2(stdin_default, {
										suppressHydrationWarning: true,
										DR_6QqGeh: SZGafHI2T,
										height: "100%",
										id: "BzUIEoIOD",
										layoutId: "BzUIEoIOD",
										qQefXa5XK: Yp26WXhzg,
										style: {
											width: "100%",
										},
										variant: "WnUthkAAH",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						<ComponentViewportProvider suppressHydrationWarning={true}>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1kpsumw-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"d__uWurak-container"}
								nodeId={"d__uWurak"}
								rendersWithMotion={true}
								scopeId={"DXioAL2NL"}
								transformTemplate={transformTemplate1}
							>
								<AvoidLayoutJumping
									suppressHydrationWarning={true}
									direction={"vertical"}
									height={"100%"}
									id={"d__uWurak"}
									layoutId={"d__uWurak"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rfO63.framer-1hspsv2, .framer-rfO63 .framer-1hspsv2 { display: block; }",
	".framer-rfO63.framer-9kveti { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 800px; }",
	".framer-rfO63 .framer-7un4vn-container, .framer-rfO63 .framer-152r329-container, .framer-rfO63 .framer-1lz8y3l-container, .framer-rfO63 .framer-gaynpv-container, .framer-rfO63 .framer-cl8yp3-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-rfO63 .framer-1kpsumw-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: auto; z-index: 1; }",
];
var FramerDXioAL2NL = withCSS(Component, css, "framer-rfO63");
var stdin_default2 = FramerDXioAL2NL;
FramerDXioAL2NL.displayName = "FAQs";
FramerDXioAL2NL.defaultProps = {
	height: 224,
	width: 800,
};
addPropertyControls2(FramerDXioAL2NL, {
	svZsCKZ7a: {
		defaultValue: "What is Framer?",
		displayTextArea: false,
		title: "Question 1",
		type: ControlType2.String,
	},
	xHGoJVa3_: {
		defaultValue:
			"Framer is a no-code tool for building and publishing responsive websites\u2014perfect for anyone creating modern, high-performance pages without coding.",
		displayTextArea: true,
		title: "Answer 1",
		type: ControlType2.String,
	},
	UV7N3G2yB: {
		defaultValue: "Do I need to know how to code to use Framer?",
		displayTextArea: false,
		title: "Question 2",
		type: ControlType2.String,
	},
	j_EfdrGoD: {
		defaultValue:
			"Framer is fully visual with no code needed, but you can still add custom code and components for more control if you're a designer or developer.",
		displayTextArea: true,
		title: "Answer 2",
		type: ControlType2.String,
	},
	IdiX4w72s: {
		defaultValue: "What is this FAQ component?",
		displayTextArea: false,
		title: "Question 3",
		type: ControlType2.String,
	},
	yIgVEHYaT: {
		defaultValue:
			"This is a free, responsive FAQ section for Framer. Drop it into any project, customize styles and text, and use it to save time on support or info pages.",
		displayTextArea: true,
		title: "Answer 3",
		type: ControlType2.String,
	},
	ApkKi7SYs: {
		defaultValue: "How do I add this FAQ component to my project?",
		displayTextArea: false,
		title: "Question 4",
		type: ControlType2.String,
	},
	rV343XnZp: {
		defaultValue:
			"After duplicating, copy and paste the component into your Framer project. Then edit the questions, answers, styles, and animations as needed.",
		displayTextArea: true,
		title: "Answer 4",
		type: ControlType2.String,
	},
	Yp26WXhzg: {
		defaultValue: "Can I customize the design of this component?",
		displayTextArea: false,
		title: "Question 5",
		type: ControlType2.String,
	},
	SZGafHI2T: {
		defaultValue:
			"Yes, absolutely. The component is built using native Framer tools, so you can tweak fonts, colors, spacing, animations, and layout however you like.",
		displayTextArea: true,
		title: "Answer 5",
		type: ControlType2.String,
	},
});
addFonts(
	FramerDXioAL2NL,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AccordionFonts,
		...LayoutJumpPreventerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:fa-qs
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaQsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var fa_qs_default = ComponentWithRoot;
export { fa_qs_default as default };
