// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-V67CEIZR.js";
import { className, css, fonts } from "./chunks/chunk-INR2ZGQA.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gPa5DBh0y7A1z8OVFPBA/6OrEG27UDZz63BidLOU5/xYePHwHxo.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/HYcHVPAbe8jLEeU7c4mp/QiycTxX7vdblEOi3o00G/Time.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	RenderTarget,
	useLocaleCode,
} from "unframer";
import {
	startTransition,
	useCallback,
	useEffect,
	useRef,
	useState,
} from "react";
var fontStack = `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`;
function formatTimeOrDate(
	outputType,
	{ showYear, showMonth, showWeekday, showMinutes, showSeconds },
	timeFormat,
	monthFormat,
	localCode,
) {
	const date = /* @__PURE__ */ new Date();
	const onlyYearIsShown = !showWeekday && !showMonth && showYear;
	switch (outputType) {
		case "date":
			return new Intl.DateTimeFormat(localCode, {
				weekday: showWeekday ? "long" : void 0,
				day: onlyYearIsShown ? void 0 : "numeric",
				month: showMonth ? monthFormat : void 0,
				year: showYear ? "numeric" : void 0,
			}).format(date);
		case "time":
			return new Intl.DateTimeFormat(localCode, {
				hour: "numeric",
				minute: showMinutes ? "numeric" : void 0,
				second: showSeconds && showMinutes ? "numeric" : void 0,
				hour12: timeFormat === "12h",
			}).format(date);
		default:
			return new Intl.DateTimeFormat(localCode).format(date);
	}
}
var defaultProps = {
	height: 20,
	width: 140,
	outputType: "time",
	color: "#999",
	timeFormat: "24h",
	showYear: true,
	showMonth: true,
	showWeekday: true,
	showMinutes: true,
	showSeconds: true,
	monthFormat: "long",
	alignment: "center",
};
function Time(props) {
	const mergedProps = {
		...defaultProps,
		...props,
	};
	const {
		outputType,
		timeFormat,
		showYear,
		showMonth,
		showWeekday,
		// showHours,
		showMinutes,
		showSeconds,
		monthFormat,
		color,
		font,
		tabularFont,
	} = mergedProps;
	const localCode = useLocaleCode();
	const getTextContent = useCallback(
		() =>
			formatTimeOrDate(
				outputType,
				{
					showYear,
					showMonth,
					showWeekday,
					// showHours,
					showMinutes,
					showSeconds,
				},
				timeFormat,
				monthFormat,
				localCode,
			),
		[
			localCode,
			monthFormat,
			outputType,
			showMinutes,
			showMonth,
			showSeconds,
			showWeekday,
			showYear,
			timeFormat,
		],
	);
	const timeoutRef = useRef();
	const updateCountdown = useCallback(
		(node) => {
			if (node === null) {
				clearTimeout(timeoutRef.current);
				return;
			}
			let prev;
			const tick = () => {
				const date = /* @__PURE__ */ new Date();
				const next =
					/* @__PURE__ */ new Date().setSeconds(date.getSeconds() + 1, 0) -
					+date;
				timeoutRef.current = setTimeout(tick, next);
				const textContent = getTextContent();
				if (prev !== textContent) {
					node.textContent = textContent;
					prev = textContent;
				}
			};
			tick();
		},
		[getTextContent],
	);
	const [visible, setIsVisible] = useState(false);
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	useEffect(() => {
		startTransition(() => setIsVisible(true));
		if (isCanvas) return;
	}, [isCanvas]);
	return (
		<p
			suppressHydrationWarning={true}
			style={{
				margin: 0,
				padding: 0,
				color,
				fontFamily: fontStack,
				fontWeight: 500,
				fontSize: 16,
				lineHeight: 1,
				visibility: visible ? "visible" : "hidden",
				...font,
				fontVariantNumeric: tabularFont ? "tabular-nums" : "normal",
				whiteSpace: "nowrap",
			}}
			ref={isCanvas ? void 0 : updateCountdown}
		>
			{getTextContent()}
		</p>
	);
}
Time.displayName = "Time & Date";
addPropertyControls(Time, {
	outputType: {
		title: "Type",
		type: ControlType.Enum,
		displaySegmentedControl: true,
		options: ["date", "time"],
		optionTitles: ["Date", "Time"],
		defaultValue: defaultProps.outputType,
	},
	showWeekday: {
		title: "Day",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showWeekday,
		hidden: (props) => props.outputType !== "date",
	},
	showMonth: {
		title: "Month",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showMonth,
		hidden: (props) => props.outputType !== "date",
	},
	monthFormat: {
		title: "Format",
		type: ControlType.Enum,
		options: ["short", "long", "numeric"],
		optionTitles: ["Short", "Long", "Numeric"],
		defaultValue: defaultProps.monthFormat,
		hidden: (props) => props.outputType !== "date" || !props.showMonth,
	},
	showYear: {
		title: "Year",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showYear,
		hidden: (props) => props.outputType !== "date",
	},
	timeFormat: {
		title: "Format",
		type: ControlType.Enum,
		options: ["12h", "24h"],
		optionTitles: ["12h", "24h"],
		displaySegmentedControl: true,
		defaultValue: defaultProps.timeFormat,
		hidden: (props) => props.outputType !== "time",
	},
	// showHours: {
	//     title: "Hours",
	//     type: ControlType.Boolean,
	//     enabledTitle: "Show",
	//     disabledTitle: "Hide",
	//     defaultValue: defaultProps.showHours,
	//     hidden: (props) => props.outputType !== "time",
	// },
	showMinutes: {
		title: "Minutes",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showMinutes,
		hidden: (props) => props.outputType !== "time",
	},
	showSeconds: {
		title: "Seconds",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showSeconds,
		hidden: (props) => props.outputType !== "time" || !props.showMinutes,
	},
	font: {
		type: ControlType.Font,
		controls: "extended",
	},
	tabularFont: {
		title: "Tabular",
		type: ControlType.Boolean,
		defaultValue: true,
	},
	color: {
		type: ControlType.Color,
		defaultValue: defaultProps.color,
	},
});

// /:https://framerusercontent.com/modules/ra3mOCNtIeDeRQIR3cxL/b1lEvkKjpJd79d1hjCpn/dQaeZcql1.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FR;InterDisplay-SemiBold",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/gazZKZuUEtvr9ULhdA4SprP0AZ0.woff2",
				weight: "600",
			},
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/pe8RoujoPxuTZhqoNzYqHX2MXA.woff2",
				weight: "600",
			},
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/teGhWnhH3bCqefKGsIsqFy3hK8.woff2",
				weight: "600",
			},
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/qQHxgTnEk6Czu1yW4xS82HQWFOk.woff2",
				weight: "600",
			},
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/MJ3N6lfN4iP5Um8rJGqLYl03tE.woff2",
				weight: "600",
			},
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/PfdOpgzFf7N2Uye9JX7xRKYTgSc.woff2",
				weight: "600",
			},
			{
				family: "Inter Display",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/0SEEmmWc3vovhaai4RlRQSWRrz0.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	'.framer-KSeYM .framer-styles-preset-nrkmii:not(.rich-text-wrapper), .framer-KSeYM .framer-styles-preset-nrkmii.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 2); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
];
var className3 = "framer-KSeYM";

// /:https://framerusercontent.com/modules/lHTza617OhEt5fpTJg9P/FmTQJDpFJN9AYlPjCRVW/KoJgeg4ep.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css4 = [
	".framer-sDQqV .framer-styles-preset-ahdeli:not(.rich-text-wrapper), .framer-sDQqV .framer-styles-preset-ahdeli.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, #f0f0f0); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-9c047fc5-acd1-4d76-b0c7-141a5b0f6204, #6e6e73); --framer-link-text-decoration: none; transition-delay: 0s; transition-duration: 0.25s; transition-property: color; transition-timing-function: cubic-bezier(0.44, 0, 0.56, 1); }",
];
var className4 = "framer-sDQqV";

// /:https://framerusercontent.com/modules/gPa5DBh0y7A1z8OVFPBA/6OrEG27UDZz63BidLOU5/xYePHwHxo.js
var TimeDateFonts = getFonts(Time);
var cycleOrder = ["to_mcXN14", "K567Rg2Bo"];
var serializationHash = "framer-tRTzE";
var variantClassNames = {
	K567Rg2Bo: "framer-v-ann22s",
	to_mcXN14: "framer-v-adc7rg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 1,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "to_mcXN14",
	Phone: "K567Rg2Bo",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "to_mcXN14",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "to_mcXN14",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2, className4];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.footer
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-adc7rg",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"to_mcXN14"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-b983c628-8813-4d0a-ac49-1485d4a45b4a, rgb(8, 8, 8))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								K567Rg2Bo: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1sry5s6"}
							data-framer-name={"Footer Container"}
							layoutDependency={layoutDependency}
							layoutId={"oQ9vTkPXA"}
							style={{
								backgroundColor:
									"var(--token-b983c628-8813-4d0a-ac49-1485d4a45b4a, rgb(8, 8, 8))",
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1xqwfq2"}
								layoutDependency={layoutDependency}
								layoutId={"YPxsmcW84"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1vmri9n"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"BnjdE6es2"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											className={"framer-styles-preset-nrkmii"}
											data-styles-preset={"dQaeZcql1"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{
												"\u041F\u043E\u0447\u043D\u0435\u043C\u043E \u0441\u0442\u0432\u043E\u0440\u044E\u0432\u0430\u0442\u0438 \u043C\u0435\u0434\u0436\u0438\u043A?"
											}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1geirpt"}
									data-framer-name={"Reach out"}
									layoutDependency={layoutDependency}
									layoutId={"gZQONMuoU"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-2txgci"}
										data-framer-name={"Reach out"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"aln05T4ct"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-yxd5fr"}
												data-styles-preset={"m15z4oKOs"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "start",
												}}
											>
												{
													"\u041D\u0410\u041F\u0418\u0428\u0406\u0422\u042C \u041D\u0410\u041C"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-flpmqq"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"YnugDb1eY"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-foyp81"}
											data-framer-name={"Instagram"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"qWwQW_wd0"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-z5k0el"}
													data-styles-preset={"ynEwEsHkm"}
												>
													<Link
														suppressHydrationWarning={true}
														href={"https://www.instagram.com/jean_gez/"}
														motionChild={true}
														nodeId={"qWwQW_wd0"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xYePHwHxo"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ahdeli"}
															data-styles-preset={"KoJgeg4ep"}
														>
															{"INSTAGRAM"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1ppfgkk"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"IOMCxgzXm"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-z5k0el"}
													data-styles-preset={"ynEwEsHkm"}
												>
													<Link
														suppressHydrationWarning={true}
														href={"https://x.com/jean_gez"}
														motionChild={true}
														nodeId={"IOMCxgzXm"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xYePHwHxo"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ahdeli"}
															data-styles-preset={"KoJgeg4ep"}
														>
															{"Telegram"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1oc7s9h"}
											data-framer-name={"Mail"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"OOKLKZstN"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-z5k0el"}
													data-styles-preset={"ynEwEsHkm"}
													dir={"auto"}
													style={{
														"--framer-text-alignment": "start",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={"mailto:hey.jeanstak@gmail.com"}
														motionChild={true}
														nodeId={"OOKLKZstN"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xYePHwHxo"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ahdeli"}
															data-styles-preset={"KoJgeg4ep"}
														>
															{"LinkedIn"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1q99qug"}
									data-framer-name={"Template info"}
									layoutDependency={layoutDependency}
									layoutId={"QrKzv_Qfe"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-18rl28b"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"iuZgfMkdW"}
									>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1cyrdai"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"bl0N4gfNO"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-yxd5fr"}
													data-styles-preset={"m15z4oKOs"}
													dir={"auto"}
													style={{
														"--framer-text-alignment": "start",
													}}
												>
													<Link
														suppressHydrationWarning={true}
														href={
															"https://jeanstore.lemonsqueezy.com/buy/241e1ae2-4b10-42af-b62a-1a9b28e0d064"
														}
														motionChild={true}
														nodeId={"bl0N4gfNO"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xYePHwHxo"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ahdeli"}
															data-styles-preset={"KoJgeg4ep"}
														>
															{"hello@27team.pro"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-1oxxnnv"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"pCcG3gAI4"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-yxd5fr"}
													data-styles-preset={"m15z4oKOs"}
												>
													<Link
														suppressHydrationWarning={true}
														href={"https://framer.link/jeanstak"}
														motionChild={true}
														nodeId={"pCcG3gAI4"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"xYePHwHxo"}
														smoothScroll={false}
													>
														<motion.a
															suppressHydrationWarning={true}
															className={"framer-styles-preset-ahdeli"}
															data-styles-preset={"KoJgeg4ep"}
														>
															{"+380 (50) 00-00-000"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-kawspw"}
										data-framer-name={"Local Data"}
										layoutDependency={layoutDependency}
										layoutId={"UgQJQYTap"}
									>
										<ComponentViewportProvider suppressHydrationWarning={true}>
											<SmartComponentScopedContainer
												suppressHydrationWarning={true}
												className={"framer-1bi6gxj-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"HoYJoB_QG-container"}
												nodeId={"HoYJoB_QG"}
												rendersWithMotion={true}
												scopeId={"xYePHwHxo"}
											>
												<Time
													suppressHydrationWarning={true}
													color={
														"var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, rgb(240, 240, 240))"
													}
													font={{
														fontFamily:
															'"Inter Display", "Inter Display Placeholder", sans-serif',
														fontSize:
															"calc(var(--framer-root-font-size, 1rem) * 0.9)",
														fontStyle: "normal",
														fontWeight: 600,
														letterSpacing: "0em",
														lineHeight: "1em",
													}}
													height={"100%"}
													id={"HoYJoB_QG"}
													layoutId={"HoYJoB_QG"}
													monthFormat={"long"}
													outputType={"time"}
													showMinutes={true}
													showMonth={true}
													showSeconds={false}
													showWeekday={true}
													showYear={true}
													tabularFont={false}
													timeFormat={"24h"}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-hg7u6l"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ORBLSiaLf"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													className={"framer-styles-preset-yxd5fr"}
													data-styles-preset={"m15z4oKOs"}
													dir={"auto"}
													style={{
														"--framer-text-alignment": "start",
													}}
												>
													{"\u041A\u0438\u0457\u0432-UA"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-5fvetm"}
									data-framer-name={"Copyright"}
									layoutDependency={layoutDependency}
									layoutId={"erZldn7gZ"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1bdm1b9"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"n784sniRV"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-yxd5fr"}
												data-styles-preset={"m15z4oKOs"}
											>
												{"\xA92026"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-dact17"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"eHmKYa_YF"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												className={"framer-styles-preset-yxd5fr"}
												data-styles-preset={"m15z4oKOs"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "start",
												}}
											>
												{
													"\u0432\u0441\u0456 \u043F\u0440\u0430\u0432\u0430 \u0437\u0430\u0445\u0438\u0449\u0435\u043D\u0456"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-zgkwim"}
								fonts={["FR;InterDisplay-Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"qrfp892V3"}
								style={{
									"--extracted-gdpscs": "rgba(240, 240, 240, 0.05)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									mask: "linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%) add",
									WebkitMask:
										"linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%) add",
								}}
								verticalAlignment={"top"}
								viewBox={"0 0 1225.8 256"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										suppressHydrationWarning={true}
										dir={"auto"}
										style={{
											"--font-selector": "RlI7SW50ZXJEaXNwbGF5LUJvbGQ=",
											"--framer-font-family":
												'"Inter Display", "Inter Display Placeholder", sans-serif',
											"--framer-font-size": "320px",
											"--framer-font-weight": "700",
											"--framer-letter-spacing": "-0.04em",
											"--framer-line-height": "0.8em",
											"--framer-text-color":
												"var(--extracted-gdpscs, rgba(240, 240, 240, 0.05))",
											"--framer-text-transform": "uppercase",
										}}
									>
										{"27TEAM"}
									</motion.h1>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	".framer-tRTzE.framer-fpw7en, .framer-tRTzE .framer-fpw7en { display: block; }",
	".framer-tRTzE.framer-adc7rg { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-tRTzE .framer-1sry5s6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 128px 16px 0px 16px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-1xqwfq2 { display: grid; flex: none; gap: 32px 32px; grid-auto-rows: 200px; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, 200px); height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-1vmri9n { align-self: start; flex: none; height: auto; justify-self: start; max-width: 480px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-tRTzE .framer-1geirpt { align-content: flex-start; align-items: flex-start; align-self: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-end; justify-self: end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-2txgci, .framer-tRTzE .framer-1cyrdai, .framer-tRTzE .framer-1oxxnnv, .framer-tRTzE .framer-hg7u6l { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-tRTzE .framer-flpmqq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-foyp81, .framer-tRTzE .framer-1ppfgkk, .framer-tRTzE .framer-1oc7s9h, .framer-tRTzE .framer-1bdm1b9, .framer-tRTzE .framer-dact17 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-tRTzE .framer-1q99qug { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: 100%; justify-content: flex-end; justify-self: start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-18rl28b, .framer-tRTzE .framer-kawspw { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-1bi6gxj-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-tRTzE .framer-5fvetm { align-content: center; align-items: center; align-self: end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; justify-self: end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-tRTzE .framer-zgkwim { flex: none; height: auto; position: relative; white-space: pre; width: 100%; }",
	".framer-tRTzE.framer-v-ann22s.framer-adc7rg { width: 390px; }",
	".framer-tRTzE.framer-v-ann22s .framer-1xqwfq2 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; justify-content: flex-end; }",
	".framer-tRTzE.framer-v-ann22s .framer-1vmri9n, .framer-tRTzE.framer-v-ann22s .framer-1geirpt, .framer-tRTzE.framer-v-ann22s .framer-5fvetm { align-self: unset; }",
	".framer-tRTzE.framer-v-ann22s .framer-1q99qug { align-self: unset; height: min-content; }",
	...css3,
	...css,
	...css2,
	...css4,
];
var FramerxYePHwHxo = withCSS(Component, css5, "framer-tRTzE");
var stdin_default = FramerxYePHwHxo;
FramerxYePHwHxo.displayName = "Footer";
FramerxYePHwHxo.defaultProps = {
	height: 820,
	width: 1200,
};
addPropertyControls2(FramerxYePHwHxo, {
	variant: {
		options: ["to_mcXN14", "K567Rg2Bo"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerxYePHwHxo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/gazZKZuUEtvr9ULhdA4SprP0AZ0.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/pe8RoujoPxuTZhqoNzYqHX2MXA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/teGhWnhH3bCqefKGsIsqFy3hK8.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/qQHxgTnEk6Czu1yW4xS82HQWFOk.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/MJ3N6lfN4iP5Um8rJGqLYl03tE.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/PfdOpgzFf7N2Uye9JX7xRKYTgSc.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/0SEEmmWc3vovhaai4RlRQSWRrz0.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/I11LrmuBDQZweplJ62KkVsklU5Y.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/UjFZPDy3qGuDktQM4q9CxhKfIa8.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/8exwVHJy2DhJ4N5prYlVMrEKmQ.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/UTeedEK21hO5jDxEUldzdScUqpg.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/Ig8B8nzy11hzIWEIYnkg91sofjo.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/qITWJ2WdG0wrgQPDb8lvnYnTXDg.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/qctQFoJqJ9aIbRSIp0AhCQpFxn8.woff2",
					weight: "700",
				},
			],
		},
		...TimeDateFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_default = ComponentWithRoot;
export { footer_default as default };
