// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Mask on' // Variant
 * imageVsible?: boolean // Image Vsible
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * video?: string // Video
 * videoVisible?: boolean // Video Visible
}} Props

 */
import { Video } from "./chunks/chunk-G23ZMBOH.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:hero-media
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8YTJwf9cuhopqJXlhm7d/I1qqHnzrhR0khFnwXq3S/CQOmPVekO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var VideoControls = getPropertyControls(Video);
var cycleOrder = ["RBBHV_4i3", "WhqGpNz9p"];
var serializationHash = "framer-9HWCU";
var variantClassNames = {
	RBBHV_4i3: "framer-v-b3lrw",
	WhqGpNz9p: "framer-v-l07ucf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mask on": "WhqGpNz9p",
	Default: "RBBHV_4i3",
};
var getProps = ({
	height,
	id,
	image,
	imageVsible,
	video,
	videoVisible,
	width,
	...props
}) => {
	return {
		...props,
		AAVz_6zhD: image ?? props.AAVz_6zhD,
		d_cG73xt0: imageVsible ?? props.d_cG73xt0 ?? true,
		GOBtbTKxd: videoVisible ?? props.GOBtbTKxd ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RBBHV_4i3",
		yp4uGzk9R: video ?? props.yp4uGzk9R,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		d_cG73xt0,
		AAVz_6zhD,
		yp4uGzk9R,
		GOBtbTKxd,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RBBHV_4i3",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-b3lrw",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"RBBHV_4i3"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-b983c628-8813-4d0a-ac49-1485d4a45b4a, rgb(0, 0, 0))",
							mask: "linear-gradient(180deg, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 1) 49.6%, rgb(0, 0, 0) 100%) add",
							opacity: 1,
							WebkitMask:
								"linear-gradient(180deg, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 1) 49.6%, rgb(0, 0, 0) 100%) add",
							...style,
						}}
						variants={{
							WhqGpNz9p: {
								mask: "linear-gradient(180deg, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0.5) 49.6%, rgba(0, 0, 0, 0) 100%) add",
								opacity: 0.75,
								WebkitMask:
									"linear-gradient(180deg, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0.5) 49.6%, rgba(0, 0, 0, 0) 100%) add",
							},
						}}
						{...addPropertyOverrides(
							{
								WhqGpNz9p: {
									"data-framer-name": "Mask on",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{d_cG73xt0 && (
							<Image
								suppressHydrationWarning={true}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 800) - 0 - 0) / 2 +
												0 +
												0),
									),
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(AAVz_6zhD),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-1lfm1q0"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"zmfCF4Gmi"}
							/>
						)}
						{GOBtbTKxd && (
							<ComponentViewportProvider suppressHydrationWarning={true}>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-hnnid8-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"RsMqUKrYd-container"}
									nodeId={"RsMqUKrYd"}
									rendersWithMotion={true}
									scopeId={"CQOmPVekO"}
								>
									<Video
										suppressHydrationWarning={true}
										backgroundColor={"rgba(0, 0, 0, 0)"}
										borderRadius={0}
										bottomLeftRadius={0}
										bottomRightRadius={0}
										controls={false}
										height={"100%"}
										id={"RsMqUKrYd"}
										isMixedBorderRadius={false}
										layoutId={"RsMqUKrYd"}
										loop={true}
										muted={true}
										objectFit={"cover"}
										playing={true}
										posterEnabled={false}
										srcFile={yp4uGzk9R}
										srcType={"Upload"}
										srcUrl={
											"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
										}
										startTime={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={0}
										topRightRadius={0}
										volume={25}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-9HWCU.framer-jxd13g, .framer-9HWCU .framer-jxd13g { display: block; }",
	".framer-9HWCU.framer-b3lrw { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 800px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-9HWCU .framer-1lfm1q0 { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-9HWCU .framer-hnnid8-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
];
var FramerCQOmPVekO = withCSS(Component, css, "framer-9HWCU");
var stdin_default = FramerCQOmPVekO;
FramerCQOmPVekO.displayName = "Hero Media";
FramerCQOmPVekO.defaultProps = {
	height: 800,
	width: 1200,
};
addPropertyControls(FramerCQOmPVekO, {
	variant: {
		options: ["RBBHV_4i3", "WhqGpNz9p"],
		optionTitles: ["Default", "Mask on"],
		title: "Variant",
		type: ControlType.Enum,
	},
	d_cG73xt0: {
		defaultValue: true,
		title: "Image Vsible",
		type: ControlType.Boolean,
	},
	AAVz_6zhD: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	yp4uGzk9R: VideoControls?.["srcFile"] && {
		...VideoControls["srcFile"],
		__defaultAssetReference: "",
		description: void 0,
		hidden: void 0,
		title: "Video",
	},
	GOBtbTKxd: {
		defaultValue: true,
		title: "Video Visible",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerCQOmPVekO,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-media
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "WhqGpNz9p",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroMediaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var hero_media_default = ComponentWithRoot;
export { hero_media_default as default };
