// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'S1' | 'S2' | 'S3' | 'S4' | 'S5' | 'S6' | 'S7' // Variant
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * image4?: {src: string, srcSet?: string, alt?: string} // Image 4
 * image5?: {src: string, srcSet?: string, alt?: string} // Image 5
 * image6?: {src: string, srcSet?: string, alt?: string} // Image 6
 * image7?: {src: string, srcSet?: string, alt?: string} // Image 7
}} Props

 */
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:service-preview
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/peHJTZPWHLzgPlY1UGRC/cV4dSL58JsYqHdSBesXU/yGygm8qtt.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"G3MqpECcq",
	"bd_NSUetd",
	"rV3XnUBMh",
	"fXy01dZbe",
	"pU2mBy6Aa",
	"PH665aobF",
	"jo5MbCRL_",
];
var serializationHash = "framer-Rpaux";
var variantClassNames = {
	bd_NSUetd: "framer-v-rhj6bo",
	fXy01dZbe: "framer-v-lmqmbg",
	G3MqpECcq: "framer-v-1zbjgj",
	jo5MbCRL_: "framer-v-zxoxn",
	PH665aobF: "framer-v-13okab0",
	pU2mBy6Aa: "framer-v-qnf1p8",
	rV3XnUBMh: "framer-v-nwck3m",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	S1: "G3MqpECcq",
	S2: "bd_NSUetd",
	S3: "rV3XnUBMh",
	S4: "fXy01dZbe",
	S5: "pU2mBy6Aa",
	S6: "PH665aobF",
	S7: "jo5MbCRL_",
};
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	image7,
	width,
	...props
}) => {
	return {
		...props,
		b_MrBkBIC: image4 ??
			props.b_MrBkBIC ?? {
				alt: "",
				pixelHeight: 4480,
				pixelWidth: 6720,
				src: "https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg 6720w",
			},
		gTuicFrIS: image7 ?? props.gTuicFrIS,
		KcIAK__UE: image2 ??
			props.KcIAK__UE ?? {
				alt: "",
				pixelHeight: 4480,
				pixelWidth: 6720,
				src: "https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg 6720w",
			},
		lf7iQC6gL: image5 ??
			props.lf7iQC6gL ?? {
				alt: "",
				pixelHeight: 4480,
				pixelWidth: 6720,
				src: "https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg 6720w",
			},
		qaalxYPZB: image3 ??
			props.qaalxYPZB ?? {
				alt: "",
				pixelHeight: 4480,
				pixelWidth: 6720,
				src: "https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg 6720w",
			},
		tTQ2CTn1R: image1 ??
			props.tTQ2CTn1R ?? {
				pixelHeight: 4480,
				pixelWidth: 6720,
				src: "https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg 6720w",
			},
		tXrIzTzCd: image6 ?? props.tXrIzTzCd,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "G3MqpECcq",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		tTQ2CTn1R,
		KcIAK__UE,
		qaalxYPZB,
		b_MrBkBIC,
		lf7iQC6gL,
		tXrIzTzCd,
		gTuicFrIS,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "G3MqpECcq",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1zbjgj",
							className,
							classNames,
						)}
						data-framer-name={"S1"}
						layoutDependency={layoutDependency}
						layoutId={"G3MqpECcq"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								bd_NSUetd: {
									"data-framer-name": "S2",
								},
								fXy01dZbe: {
									"data-framer-name": "S4",
								},
								jo5MbCRL_: {
									"data-framer-name": "S7",
								},
								PH665aobF: {
									"data-framer-name": "S6",
								},
								pU2mBy6Aa: {
									"data-framer-name": "S5",
								},
								rV3XnUBMh: {
									"data-framer-name": "S3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							suppressHydrationWarning={true}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 150) - 0 - 300) / 2),
								),
								sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
								...toResponsiveImage(tTQ2CTn1R),
							}}
							className={"framer-1h54y26"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"i5iW7Hh9a"}
							{...addPropertyOverrides(
								{
									bd_NSUetd: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 150) - 0 - 300) / 2),
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(KcIAK__UE),
										},
									},
									fXy01dZbe: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 150) - 0 - 300) / 2),
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(b_MrBkBIC),
										},
									},
									jo5MbCRL_: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 150) - 0 - 300) / 2),
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(gTuicFrIS),
										},
									},
									PH665aobF: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 150) - 0 - 300) / 2),
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(tXrIzTzCd),
										},
									},
									pU2mBy6Aa: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 150) - 0 - 300) / 2),
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(lf7iQC6gL),
										},
									},
									rV3XnUBMh: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 150) - 0 - 300) / 2),
											),
											sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
											...toResponsiveImage(qaalxYPZB),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Rpaux.framer-hw6axg, .framer-Rpaux .framer-hw6axg { display: block; }",
	".framer-Rpaux.framer-1zbjgj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 200px; }",
	".framer-Rpaux .framer-1h54y26 { aspect-ratio: 1.3333333333333333 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 150px); overflow: visible; position: relative; width: 1px; }",
];
var FrameryGygm8qtt = withCSS(Component, css, "framer-Rpaux");
var stdin_default = FrameryGygm8qtt;
FrameryGygm8qtt.displayName = "Service Preview";
FrameryGygm8qtt.defaultProps = {
	height: 150,
	width: 200,
};
addPropertyControls(FrameryGygm8qtt, {
	variant: {
		options: [
			"G3MqpECcq",
			"bd_NSUetd",
			"rV3XnUBMh",
			"fXy01dZbe",
			"pU2mBy6Aa",
			"PH665aobF",
			"jo5MbCRL_",
		],
		optionTitles: ["S1", "S2", "S3", "S4", "S5", "S6", "S7"],
		title: "Variant",
		type: ControlType.Enum,
	},
	tTQ2CTn1R: {
		__defaultAssetReference:
			"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	KcIAK__UE: {
		__defaultAssetReference:
			"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		},
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	qaalxYPZB: {
		__defaultAssetReference:
			"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		},
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	b_MrBkBIC: {
		__defaultAssetReference:
			"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		},
		title: "Image 4",
		type: ControlType.ResponsiveImage,
	},
	lf7iQC6gL: {
		__defaultAssetReference:
			"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jLTYqaWLAwUarcaZ2lPy7EmXZTU.jpg?originalFilename=pexels-cottonbro-8717526.jpg&preferredSize=auto",
		},
		title: "Image 5",
		type: ControlType.ResponsiveImage,
	},
	tXrIzTzCd: {
		title: "Image 6",
		type: ControlType.ResponsiveImage,
	},
	gTuicFrIS: {
		title: "Image 7",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FrameryGygm8qtt,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-preview
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "G3MqpECcq",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicePreviewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var service_preview_default = ComponentWithRoot;
export { service_preview_default as default };
