// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-YIX4HD6O.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-INR2ZGQA.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:submit-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4SxKY9LXWeOwQBOtym3v/xibGWojnJUnJGJyYByb2/j0o6JWu5v.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	lQYpkuI6D: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"lQYpkuI6D",
	"c5_fXqDcm",
	"ubzBrpDXl",
	"jFgpqHmUo",
	"aDKbZM9O1",
];
var serializationHash = "framer-i7IB6";
var variantClassNames = {
	aDKbZM9O1: "framer-v-1fd56lz",
	c5_fXqDcm: "framer-v-1v7qqwy",
	jFgpqHmUo: "framer-v-hjuwkm",
	lQYpkuI6D: "framer-v-15ze0ym",
	ubzBrpDXl: "framer-v-194ks57",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "lQYpkuI6D",
	Disabled: "ubzBrpDXl",
	Error: "aDKbZM9O1",
	Loading: "c5_fXqDcm",
	Success: "jFgpqHmUo",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lQYpkuI6D",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lQYpkuI6D",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "c5_fXqDcm") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "c5_fXqDcm") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.button
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-15ze0ym",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"lQYpkuI6D"}
						ref={refBinding}
						style={{
							opacity: 1,
							...style,
						}}
						variants={{
							"lQYpkuI6D-hover": {
								opacity: 1,
							},
							"lQYpkuI6D-pressed": {
								opacity: 1,
							},
							aDKbZM9O1: {
								opacity: 1,
							},
							jFgpqHmUo: {
								opacity: 1,
							},
							ubzBrpDXl: {
								opacity: 0.5,
							},
						}}
						{...addPropertyOverrides(
							{
								aDKbZM9O1: {
									"data-framer-name": "Error",
								},
								c5_fXqDcm: {
									"data-framer-name": "Loading",
								},
								jFgpqHmUo: {
									"data-framer-name": "Success",
								},
								ubzBrpDXl: {
									"data-framer-name": "Disabled",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-f10vmq"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ECC0eC0Xq"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-9c047fc5-acd1-4d76-b0c7-141a5b0f6204, rgb(110, 110, 115))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								variants={{
									"lQYpkuI6D-hover": {
										"--extracted-r6o4lv":
											"var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, rgb(240, 240, 240))",
									},
									"lQYpkuI6D-pressed": {
										"--extracted-r6o4lv":
											"var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, rgb(240, 240, 240))",
									},
									aDKbZM9O1: {
										"--extracted-r6o4lv": "rgb(201, 32, 32)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"lQYpkuI6D-hover": {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1x3sb3c"}
														data-styles-preset={"oNyEAuEE4"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "start",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, rgb(240, 240, 240)))",
														}}
													>
														{
															"\u041D\u0430\u0434\u0456\u0441\u043B\u0430\u0442\u0438"
														}
													</motion.p>
												</React.Fragment>
											),
										},
										"lQYpkuI6D-pressed": {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1x3sb3c"}
														data-styles-preset={"oNyEAuEE4"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "start",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-83804f45-2c43-4b13-aa1a-ff2551018d96, rgb(240, 240, 240)))",
														}}
													>
														{
															"\u041D\u0430\u0434\u0456\u0441\u043B\u0430\u0442\u0438"
														}
													</motion.p>
												</React.Fragment>
											),
										},
										aDKbZM9O1: {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														className={"framer-styles-preset-yxd5fr"}
														data-styles-preset={"m15z4oKOs"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(201, 32, 32))",
														}}
													>
														{"ERROR"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-1x3sb3c"}
										data-styles-preset={"oNyEAuEE4"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "start",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-9c047fc5-acd1-4d76-b0c7-141a5b0f6204, rgb(110, 110, 115)))",
										}}
									>
										{"\u041D\u0430\u0434\u0456\u0441\u043B\u0430\u0442\u0438"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1nkmryh"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"Ejd0Sgy89"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									suppressHydrationWarning={true}
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1km508t"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"SqfbCXUzs"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										c5_fXqDcm: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1mrq37"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"je29VRgzz"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	".framer-i7IB6.framer-1lr8got, .framer-i7IB6 .framer-1lr8got { display: block; }",
	".framer-i7IB6.framer-15ze0ym { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-i7IB6 .framer-f10vmq { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-i7IB6 .framer-1nkmryh { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: auto; overflow: hidden; position: relative; width: 20px; }",
	".framer-i7IB6 .framer-1km508t { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-i7IB6 .framer-1mrq37 { aspect-ratio: 1 / 1; flex: none; height: auto; left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-i7IB6.framer-v-1v7qqwy.framer-15ze0ym, .framer-i7IB6.framer-v-194ks57.framer-15ze0ym, .framer-i7IB6.framer-v-hjuwkm.framer-15ze0ym, .framer-i7IB6.framer-v-1fd56lz.framer-15ze0ym { cursor: unset; }",
	".framer-i7IB6.framer-v-1v7qqwy .framer-1km508t { overflow: hidden; }",
	...css,
	...css2,
];
var Framerj0o6JWu5v = withCSS(Component, css3, "framer-i7IB6");
var stdin_default = Framerj0o6JWu5v;
Framerj0o6JWu5v.displayName = "Submit Button";
Framerj0o6JWu5v.defaultProps = {
	height: 29,
	width: 90,
};
addPropertyControls(Framerj0o6JWu5v, {
	variant: {
		options: ["lQYpkuI6D", "c5_fXqDcm", "ubzBrpDXl", "jFgpqHmUo", "aDKbZM9O1"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerj0o6JWu5v,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:submit-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SubmitButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var submit_button_default = ComponentWithRoot;
export { submit_button_default as default };
