// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * teamRole?: string // Team Role
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-YIX4HD6O.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/P9pkuNLl2vLnmCTGG5O5/1AqCqZvczwvTFcNzebyD/lEueghCeT.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-tN0fu";
var variantClassNames = {
	npP5ohfmL: "framer-v-z1p3p1",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, name1, teamRole, width, ...props }) => {
	return {
		...props,
		Cy7KsG98l: name1 ?? props.Cy7KsG98l ?? "Name",
		IEuiQxg64: image ?? props.IEuiQxg64,
		MGQob_5Vz: teamRole ?? props.MGQob_5Vz ?? "Team Role",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		IEuiQxg64,
		Cy7KsG98l,
		MGQob_5Vz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "npP5ohfmL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-z1p3p1",
							className2,
							classNames,
						)}
						data-framer-name={"Card"}
						layoutDependency={layoutDependency}
						layoutId={"npP5ohfmL"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<Image
							suppressHydrationWarning={true}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0 + 0,
								),
								pixelHeight: 4480,
								pixelWidth: 6720,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(IEuiQxg64),
							}}
							className={"framer-96haph"}
							data-framer-name={"Team Picture"}
							layoutDependency={layoutDependency}
							layoutId={"Pl1mNC89_"}
						/>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-q2ucz"}
							data-framer-name={"Info"}
							layoutDependency={layoutDependency}
							layoutId={"mOpv7V9ol"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-z5zmw2"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"nUQ9mbpq7"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Cy7KsG98l}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-1x3sb3c"}
										data-styles-preset={"oNyEAuEE4"}
									>
										{"Jhon M"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-14ibxi2"}
								data-framer-name={"Team Role"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"zDvkcpgAi"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-9c047fc5-acd1-4d76-b0c7-141a5b0f6204, rgb(110, 110, 115))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={MGQob_5Vz}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										className={"framer-styles-preset-1x3sb3c"}
										data-styles-preset={"oNyEAuEE4"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-9c047fc5-acd1-4d76-b0c7-141a5b0f6204, rgb(110, 110, 115)))",
										}}
									>
										{"CEO"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-tN0fu.framer-1jynd9y, .framer-tN0fu .framer-1jynd9y { display: block; }",
	".framer-tN0fu.framer-z1p3p1 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 569px; }",
	".framer-tN0fu .framer-96haph { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 427px); overflow: hidden; position: relative; width: 100%; }",
	".framer-tN0fu .framer-q2ucz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-tN0fu .framer-z5zmw2, .framer-tN0fu .framer-14ibxi2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FramerlEueghCeT = withCSS(Component, css2, "framer-tN0fu");
var stdin_default = FramerlEueghCeT;
FramerlEueghCeT.displayName = "Team Card";
FramerlEueghCeT.defaultProps = {
	height: 463,
	width: 569,
};
addPropertyControls(FramerlEueghCeT, {
	IEuiQxg64: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	Cy7KsG98l: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	MGQob_5Vz: {
		defaultValue: "Team Role",
		displayTextArea: false,
		title: "Team Role",
		type: ControlType.String,
	},
});
addFonts(
	FramerlEueghCeT,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
