// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 9ea48a1aa2eafa92 "27PREMIUM", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Grid 3' | 'Grid 2' | 'List' | 'Phone-Img' | 'Phone-List' // Variant
 * cursor?: any // Cursor
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-5EXG6PUH.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-VP67KBTB.js";
import { stdin_default } from "./chunks/chunk-DY3YN3KF.js";
import "./chunks/chunk-G23ZMBOH.js";
import "./chunks/chunk-YIX4HD6O.js";
import "./chunks/chunk-INR2ZGQA.js";
import { routes } from "./chunks/chunk-WNTOGGO6.js";

// virtual:work-view
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/njWZzecLs03xuhZxMZYH/wHJZeY1UvD9aB3mBrky3/yKjC3yof7.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	Floating,
	getFonts,
	PathVariablesContext,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useDynamicRefs,
	useLocaleInfo,
	useOverlayState,
	useQueryData,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js
import {
	addPropertyControls as e6,
	ControlType as l3,
	QueryEngine as t3,
} from "unframer";

// /:https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF-0.js
import { ControlType as y } from "unframer";
import { ControlType as P } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function t(t22, e52, r22) {
	return (
		e52 in t22
			? Object.defineProperty(t22, e52, {
					value: r22,
					enumerable: true,
					configurable: true,
					writable: true,
				})
			: (t22[e52] = r22),
		t22
	);
}
var e;
var r;
var n = Object.create;
var i = Object.defineProperty;
var s = Object.getOwnPropertyDescriptor;
var a = Object.getOwnPropertyNames;
var o = Object.getPrototypeOf;
var u = Object.prototype.hasOwnProperty;
var l = (t22, e52) =>
	function () {
		try {
			return (
				e52 ||
					(0, t22[a(t22)[0]])(
						(e52 = {
							exports: {},
						}).exports,
						e52,
					),
				e52.exports
			);
		} catch (t32) {
			throw ((e52 = 0), t32);
		}
	};
var h = (t22, e52, r22, n22) => {
	if ((e52 && "object" == typeof e52) || "function" == typeof e52)
		for (let o22 of a(e52))
			u.call(t22, o22) ||
				o22 === r22 ||
				i(t22, o22, {
					get: () => e52[o22],
					enumerable: !(n22 = s(e52, o22)) || n22.enumerable,
				});
	return t22;
};
var c = (t22, e52, r22) => (
	(r22 = null != t22 ? n(o(t22)) : {}),
	h(
		// If the importer is in node compatibility mode or this is not an ESM
		// file that has been converted to a CommonJS file using a Babel-
		// compatible transform (i.e. "__esModule" has not been set), then set
		// "default" to the CommonJS "module.exports" for node compatibility.
		!e52 && t22 && t22.__esModule
			? r22
			: i(r22, "default", {
					value: t22,
					enumerable: true,
				}),
		t22,
	)
);
var f = l({
	"../../../node_modules/dataloader/index.js"(t22, e52) {
		var r22,
			n22 = /* @__PURE__ */ (function () {
				function t32(t4, e7) {
					if ("function" != typeof t4)
						throw TypeError(
							"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but got: " +
								t4 +
								".",
						);
					(this._batchLoadFn = t4),
						(this._maxBatchSize = (function (t5) {
							if (!(!t5 || false !== t5.batch)) return 1;
							var e8 = t5 && t5.maxBatchSize;
							if (void 0 === e8) return 1 / 0;
							if ("number" != typeof e8 || e8 < 1)
								throw TypeError(
									"maxBatchSize must be a positive number: " + e8,
								);
							return e8;
						})(e7)),
						(this._batchScheduleFn = (function (t5) {
							var e8 = t5 && t5.batchScheduleFn;
							if (void 0 === e8) return i22;
							if ("function" != typeof e8)
								throw TypeError("batchScheduleFn must be a function: " + e8);
							return e8;
						})(e7)),
						(this._cacheKeyFn = (function (t5) {
							var e8 = t5 && t5.cacheKeyFn;
							if (void 0 === e8)
								return function (t6) {
									return t6;
								};
							if ("function" != typeof e8)
								throw TypeError("cacheKeyFn must be a function: " + e8);
							return e8;
						})(e7)),
						(this._cacheMap = (function (t5) {
							if (!(!t5 || false !== t5.cache)) return null;
							var e8 = t5 && t5.cacheMap;
							if (void 0 === e8) return /* @__PURE__ */ new Map();
							if (null !== e8) {
								var r3 = ["get", "set", "delete", "clear"].filter(
									function (t6) {
										return e8 && "function" != typeof e8[t6];
									},
								);
								if (0 !== r3.length)
									throw TypeError(
										"Custom cacheMap missing methods: " + r3.join(", "),
									);
							}
							return e8;
						})(e7)),
						(this._batch = null),
						(this.name = e7 && e7.name ? e7.name : null);
				}
				var e62 = t32.prototype;
				return (
					(e62.load = function (t4) {
						if (null == t4)
							throw TypeError(
								"The loader.load() function must be called with a value, but got: " +
									String(t4) +
									".",
							);
						var e7 = (function (t5) {
								var e8 = t5._batch;
								if (
									null !== e8 &&
									!e8.hasDispatched &&
									e8.keys.length < t5._maxBatchSize
								)
									return e8;
								var r4 = {
									hasDispatched: false,
									keys: [],
									callbacks: [],
								};
								return (
									(t5._batch = r4),
									t5._batchScheduleFn(function () {
										(function (t6, e9) {
											var r5;
											if (((e9.hasDispatched = true), 0 === e9.keys.length)) {
												a22(e9);
												return;
											}
											try {
												r5 = t6._batchLoadFn(e9.keys);
											} catch (r6) {
												return s22(
													t6,
													e9,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function errored synchronously: " +
															String(r6) +
															".",
													),
												);
											}
											if (!r5 || "function" != typeof r5.then)
												return s22(
													t6,
													e9,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise: " +
															String(r5) +
															".",
													),
												);
											r5.then(function (t7) {
												if (!o22(t7))
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array: " +
															String(t7) +
															".",
													);
												if (t7.length !== e9.keys.length)
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\n" +
															String(e9.keys) +
															"\n\nValues:\n" +
															String(t7),
													);
												a22(e9);
												for (var r6 = 0; r6 < e9.callbacks.length; r6++) {
													var n4 = t7[r6];
													n4 instanceof Error
														? e9.callbacks[r6].reject(n4)
														: e9.callbacks[r6].resolve(n4);
												}
											}).catch(function (r6) {
												s22(t6, e9, r6);
											});
										})(t5, r4);
									}),
									r4
								);
							})(this),
							r3 = this._cacheMap,
							n32 = this._cacheKeyFn(t4);
						if (r3) {
							var i3 = r3.get(n32);
							if (i3) {
								var u22 = e7.cacheHits || (e7.cacheHits = []);
								return new Promise(function (t5) {
									u22.push(function () {
										t5(i3);
									});
								});
							}
						}
						e7.keys.push(t4);
						var l22 = new Promise(function (t5, r4) {
							e7.callbacks.push({
								resolve: t5,
								reject: r4,
							});
						});
						return r3 && r3.set(n32, l22), l22;
					}),
					(e62.loadMany = function (t4) {
						if (!o22(t4))
							throw TypeError(
								"The loader.loadMany() function must be called with Array<key> but got: " +
									t4 +
									".",
							);
						for (var e7 = [], r3 = 0; r3 < t4.length; r3++)
							e7.push(
								this.load(t4[r3]).catch(function (t5) {
									return t5;
								}),
							);
						return Promise.all(e7);
					}),
					(e62.clear = function (t4) {
						var e7 = this._cacheMap;
						if (e7) {
							var r3 = this._cacheKeyFn(t4);
							e7.delete(r3);
						}
						return this;
					}),
					(e62.clearAll = function () {
						var t4 = this._cacheMap;
						return t4 && t4.clear(), this;
					}),
					(e62.prime = function (t4, e7) {
						var r3 = this._cacheMap;
						if (r3) {
							var n32,
								i3 = this._cacheKeyFn(t4);
							void 0 === r3.get(i3) &&
								(e7 instanceof Error
									? (n32 = Promise.reject(e7)).catch(function () {})
									: (n32 = Promise.resolve(e7)),
								r3.set(i3, n32));
						}
						return this;
					}),
					t32
				);
			})(),
			i22 =
				"object" == typeof process && "function" == typeof process.nextTick
					? function (t32) {
							r22 || (r22 = Promise.resolve()),
								r22.then(function () {
									process.nextTick(t32);
								});
						}
					: "function" == typeof setImmediate
						? function (t32) {
								setImmediate(t32);
							}
						: function (t32) {
								setTimeout(t32);
							};
		function s22(t32, e62, r3) {
			a22(e62);
			for (var n32 = 0; n32 < e62.keys.length; n32++)
				t32.clear(e62.keys[n32]), e62.callbacks[n32].reject(r3);
		}
		function a22(t32) {
			if (t32.cacheHits)
				for (var e62 = 0; e62 < t32.cacheHits.length; e62++)
					t32.cacheHits[e62]();
		}
		function o22(t32) {
			return (
				"object" == typeof t32 &&
				null !== t32 &&
				"number" == typeof t32.length &&
				(0 === t32.length ||
					(t32.length > 0 &&
						Object.prototype.hasOwnProperty.call(t32, t32.length - 1)))
			);
		}
		e52.exports = n22;
	},
});
var d = c(f(), 1);
var g = {
	Uint8: 1,
	Uint16: 2,
	Uint32: 4,
	BigUint64: 8,
	Int8: 1,
	Int16: 2,
	Int32: 4,
	BigInt64: 8,
	Float32: 4,
	Float64: 8,
};
var v =
	((e = class e2 {
		getOffset() {
			return this.offset;
		}
		ensureLength(t22) {
			let e52 = this.bytes.length;
			if (!(this.offset + t22 <= e52)) throw Error("Reading out of bounds");
		}
		readUint8() {
			let t22 = g.Uint8;
			this.ensureLength(t22);
			let e52 = this.view.getUint8(this.offset);
			return (this.offset += t22), e52;
		}
		readUint16() {
			let t22 = g.Uint16;
			this.ensureLength(t22);
			let e52 = this.view.getUint16(this.offset);
			return (this.offset += t22), e52;
		}
		readUint32() {
			let t22 = g.Uint32;
			this.ensureLength(t22);
			let e52 = this.view.getUint32(this.offset);
			return (this.offset += t22), e52;
		}
		readUint64() {
			let t22 = this.readBigUint64();
			return Number(t22);
		}
		readBigUint64() {
			let t22 = g.BigUint64;
			this.ensureLength(t22);
			let e52 = this.view.getBigUint64(this.offset);
			return (this.offset += t22), e52;
		}
		readInt8() {
			let t22 = g.Int8;
			this.ensureLength(t22);
			let e52 = this.view.getInt8(this.offset);
			return (this.offset += t22), e52;
		}
		readInt16() {
			let t22 = g.Int16;
			this.ensureLength(t22);
			let e52 = this.view.getInt16(this.offset);
			return (this.offset += t22), e52;
		}
		readInt32() {
			let t22 = g.Int32;
			this.ensureLength(t22);
			let e52 = this.view.getInt32(this.offset);
			return (this.offset += t22), e52;
		}
		readInt64() {
			let t22 = this.readBigInt64();
			return Number(t22);
		}
		readBigInt64() {
			let t22 = g.BigInt64;
			this.ensureLength(t22);
			let e52 = this.view.getBigInt64(this.offset);
			return (this.offset += t22), e52;
		}
		readFloat32() {
			let t22 = g.Float32;
			this.ensureLength(t22);
			let e52 = this.view.getFloat32(this.offset);
			return (this.offset += t22), e52;
		}
		readFloat64() {
			let t22 = g.Float64;
			this.ensureLength(t22);
			let e52 = this.view.getFloat64(this.offset);
			return (this.offset += t22), e52;
		}
		readBytes(t22) {
			let e52 = this.offset,
				r22 = e52 + t22,
				n22 = this.bytes.subarray(e52, r22);
			return (this.offset = r22), n22;
		}
		readString() {
			let t22 = this.readUint32(),
				r22 = this.readBytes(t22);
			return e2.textDecoder.decode(r22);
		}
		readJson() {
			let t22 = this.readString();
			return JSON.parse(t22);
		}
		constructor(e52) {
			t(this, "bytes", void 0),
				t(this, "offset", 0),
				t(this, "view", void 0),
				(this.bytes = e52),
				(this.view = p(this.bytes));
		}
	}),
	// TextDecoder has no per-decode state unless streaming is enabled. Reusing one class-owned decoder
	// avoids constructing one for every CMS item, where each item gets its own BufferReader.
	t(e, "textDecoder", new TextDecoder()),
	e);
function p(t22) {
	return new DataView(t22.buffer, t22.byteOffset, t22.byteLength);
}
var m = "undefined" != typeof __unframerWindow;
var w = m && "function" == typeof __unframerWindow.requestIdleCallback;
function I(t22, ...e52) {
	if (!t22)
		throw Error(
			"Assertion Error" + (e52.length > 0 ? ": " + e52.join(" ") : ""),
		);
}
function b(t22) {
	throw Error(`Unexpected value: ${t22}`);
}
var U = 1024;
var S = 1.5;
var k = (t22) => 2 ** t22 - 1;
var L = (t22) => -(2 ** (t22 - 1));
var B = (t22) => 2 ** (t22 - 1) - 1;
var E = {
	Uint8: 0,
	Uint16: 0,
	Uint32: 0,
	Uint64: 0,
	BigUint64: 0,
	Int8: L(8),
	Int16: L(16),
	Int32: L(32),
	Int64: Number.MIN_SAFE_INTEGER,
	BigInt64: -(BigInt(2) ** BigInt(63)),
};
var T = {
	Uint8: k(8),
	Uint16: k(16),
	Uint32: k(32),
	Uint64: Number.MAX_SAFE_INTEGER,
	BigUint64: BigInt(2) ** BigInt(64) - BigInt(1),
	Int8: B(8),
	Int16: B(16),
	Int32: B(32),
	Int64: Number.MAX_SAFE_INTEGER,
	BigInt64: BigInt(2) ** BigInt(63) - BigInt(1),
};
function M(t22, e52, r22, n22) {
	I(t22 >= e52, t22, "outside lower bound for", n22),
		I(t22 <= r22, t22, "outside upper bound for", n22);
}
var F = class {
	getOffset() {
		return this.offset;
	}
	slice(t22 = 0, e52 = this.offset) {
		return this.bytes.slice(t22, e52);
	}
	subarray(t22 = 0, e52 = this.offset) {
		return this.bytes.subarray(t22, e52);
	}
	ensureLength(t22) {
		let e52 = this.bytes.length;
		if (this.offset + t22 <= e52) return;
		let r22 = new Uint8Array(Math.ceil(e52 * S) + t22);
		r22.set(this.bytes), (this.bytes = r22), (this.view = p(r22));
	}
	writeUint8(t22) {
		M(t22, E.Uint8, T.Uint8, "Uint8");
		let e52 = g.Uint8;
		this.ensureLength(e52),
			this.view.setUint8(this.offset, t22),
			(this.offset += e52);
	}
	writeUint16(t22) {
		M(t22, E.Uint16, T.Uint16, "Uint16");
		let e52 = g.Uint16;
		this.ensureLength(e52),
			this.view.setUint16(this.offset, t22),
			(this.offset += e52);
	}
	writeUint32(t22) {
		M(t22, E.Uint32, T.Uint32, "Uint32");
		let e52 = g.Uint32;
		this.ensureLength(e52),
			this.view.setUint32(this.offset, t22),
			(this.offset += e52);
	}
	writeUint64(t22) {
		M(t22, E.Uint64, T.Uint64, "Uint64");
		let e52 = BigInt(t22);
		this.writeBigUint64(e52);
	}
	writeBigUint64(t22) {
		M(t22, E.BigUint64, T.BigUint64, "BigUint64");
		let e52 = g.BigUint64;
		this.ensureLength(e52),
			this.view.setBigUint64(this.offset, t22),
			(this.offset += e52);
	}
	writeInt8(t22) {
		M(t22, E.Int8, T.Int8, "Int8");
		let e52 = g.Int8;
		this.ensureLength(e52),
			this.view.setInt8(this.offset, t22),
			(this.offset += e52);
	}
	writeInt16(t22) {
		M(t22, E.Int16, T.Int16, "Int16");
		let e52 = g.Int16;
		this.ensureLength(e52),
			this.view.setInt16(this.offset, t22),
			(this.offset += e52);
	}
	writeInt32(t22) {
		M(t22, E.Int32, T.Int32, "Int32");
		let e52 = g.Int32;
		this.ensureLength(e52),
			this.view.setInt32(this.offset, t22),
			(this.offset += e52);
	}
	writeInt64(t22) {
		M(t22, E.Int64, T.Int64, "Int64");
		let e52 = BigInt(t22);
		this.writeBigInt64(e52);
	}
	writeBigInt64(t22) {
		M(t22, E.BigInt64, T.BigInt64, "BigInt64");
		let e52 = g.BigInt64;
		this.ensureLength(e52),
			this.view.setBigInt64(this.offset, t22),
			(this.offset += e52);
	}
	writeFloat32(t22) {
		let e52 = g.Float32;
		this.ensureLength(e52),
			this.view.setFloat32(this.offset, t22),
			(this.offset += e52);
	}
	writeFloat64(t22) {
		let e52 = g.Float64;
		this.ensureLength(e52),
			this.view.setFloat64(this.offset, t22),
			(this.offset += e52);
	}
	writeBytes(t22) {
		let e52 = t22.length;
		this.ensureLength(e52),
			this.bytes.set(t22, this.offset),
			(this.offset += e52);
	}
	encodeString(t22) {
		let e52 = this.encodedStrings.get(t22);
		if (e52) return e52;
		let r22 = this.encoder.encode(t22);
		return this.encodedStrings.set(t22, r22), r22;
	}
	writeString(t22) {
		let e52 = this.encodeString(t22),
			r22 = e52.length;
		this.writeUint32(r22), this.writeBytes(e52);
	}
	writeJson(t22) {
		let e52 = JSON.stringify(t22);
		this.writeString(e52);
	}
	constructor() {
		t(this, "offset", 0),
			t(this, "bytes", new Uint8Array(U)),
			t(this, "view", p(this.bytes)),
			t(this, "encoder", new TextEncoder()),
			t(this, "encodedStrings", /* @__PURE__ */ new Map());
	}
};
function x(t22) {
	return "string" == typeof t22;
}
function N(t22) {
	return Number.isFinite(t22);
}
function A(t22) {
	return null === t22;
}
var O = class e3 {
	static fromString(t22) {
		let [r22, n22, i22] = t22.split("/").map(Number);
		return (
			I(N(r22), "Invalid chunkId"),
			I(N(n22), "Invalid offset"),
			I(N(i22), "Invalid length"),
			new e3(r22, n22, i22)
		);
	}
	toString() {
		return `${this.chunkId}/${this.offset}/${this.length}`;
	}
	static read(t22) {
		let r22 = t22.readUint16(),
			n22 = t22.readUint32(),
			i22 = t22.readUint32();
		return new e3(r22, n22, i22);
	}
	write(t22) {
		t22.writeUint16(this.chunkId),
			t22.writeUint32(this.offset),
			t22.writeUint32(this.length);
	}
	compare(t22) {
		return this.chunkId < t22.chunkId
			? -1
			: this.chunkId > t22.chunkId
				? 1
				: this.offset < t22.offset
					? -1
					: this.offset > t22.offset
						? 1
						: (I(this.length === t22.length), 0);
	}
	constructor(e52, r22, n22) {
		t(this, "chunkId", void 0),
			t(this, "offset", void 0),
			t(this, "length", void 0),
			(this.chunkId = e52),
			(this.offset = r22),
			(this.length = n22);
	}
};
function R(t22) {
	if (A(t22)) return 0;
	switch (t22.type) {
		case P.Array:
			return 1;
		case P.Boolean:
			return 2;
		case P.Color:
			return 3;
		case P.Date:
			return 4;
		case P.Enum:
			return 5;
		case P.File:
			return 6;
		case P.ResponsiveImage:
			return 10;
		case P.Link:
			return 7;
		case P.Number:
			return 8;
		case P.Object:
			return 9;
		case P.RichText:
			return 11;
		case P.String:
			return 12;
		case P.VectorSetItem:
			return 13;
		default:
			b(t22);
	}
}
function q(t22) {
	let e52 = t22.readUint16(),
		n22 = [];
	for (let i22 = 0; i22 < e52; i22++) {
		let e62 = r.read(t22);
		n22.push(e62);
	}
	return {
		type: P.Array,
		value: n22,
	};
}
function _(t22, e52) {
	for (let n22 of (t22.writeUint16(e52.value.length), e52.value))
		r.write(t22, n22);
}
function j(t22, e52, n22) {
	let i22 = t22.value.length,
		s22 = e52.value.length;
	if (i22 < s22) return -1;
	if (i22 > s22) return 1;
	for (let s32 = 0; s32 < i22; s32++) {
		let i3 = t22.value[s32],
			a22 = e52.value[s32],
			o22 = r.compare(i3, a22, n22);
		if (0 !== o22) return o22;
	}
	return 0;
}
function D(t22) {
	return {
		type: P.Boolean,
		value: 0 !== t22.readUint8(),
	};
}
function C(t22, e52) {
	t22.writeUint8(e52.value ? 1 : 0);
}
function J(t22, e52) {
	return t22.value < e52.value ? -1 : t22.value > e52.value ? 1 : 0;
}
function V(t22) {
	return {
		type: P.Color,
		value: t22.readString(),
	};
}
function W(t22, e52) {
	t22.writeString(e52.value);
}
function $(t22, e52) {
	return t22.value < e52.value ? -1 : t22.value > e52.value ? 1 : 0;
}
function z(t22) {
	let e52 = t22.readInt64(),
		r22 = new Date(e52);
	return {
		type: P.Date,
		value: r22.toISOString(),
	};
}
function G(t22, e52) {
	let r22 = new Date(e52.value),
		n22 = r22.getTime();
	t22.writeInt64(n22);
}
function K(t22, e52) {
	let r22 = new Date(t22.value),
		n22 = new Date(e52.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function H(t22) {
	return {
		type: P.Enum,
		value: t22.readString(),
	};
}
function X(t22, e52) {
	t22.writeString(e52.value);
}
function Q(t22, e52) {
	return t22.value < e52.value ? -1 : t22.value > e52.value ? 1 : 0;
}
function Y(t22) {
	return {
		type: P.File,
		value: t22.readString(),
	};
}
function Z(t22, e52) {
	t22.writeString(e52.value);
}
function tt(t22, e52) {
	return t22.value < e52.value ? -1 : t22.value > e52.value ? 1 : 0;
}
function te(t22) {
	return {
		type: P.Link,
		value: t22.readJson(),
	};
}
function tr(t22, e52) {
	t22.writeJson(e52.value);
}
function tn(t22, e52) {
	let r22 = JSON.stringify(t22.value),
		n22 = JSON.stringify(e52.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function ti(t22) {
	return {
		type: P.Number,
		value: t22.readFloat64(),
	};
}
function ts(t22, e52) {
	t22.writeFloat64(e52.value);
}
function ta(t22, e52) {
	return t22.value < e52.value ? -1 : t22.value > e52.value ? 1 : 0;
}
function to(t22) {
	let e52 = t22.readUint16(),
		n22 = {};
	for (let i22 = 0; i22 < e52; i22++) {
		let e62 = t22.readString();
		n22[e62] = r.read(t22);
	}
	return {
		type: P.Object,
		value: n22,
	};
}
function tu(t22, e52) {
	let n22 = Object.entries(e52.value);
	for (let [e62, i22] of (t22.writeUint16(n22.length), n22))
		t22.writeString(e62), r.write(t22, i22);
}
function tl(t22, e52, n22) {
	let i22 = Object.keys(t22.value).sort(),
		s22 = Object.keys(e52.value).sort();
	if (i22.length < s22.length) return -1;
	if (i22.length > s22.length) return 1;
	for (let a22 = 0; a22 < i22.length; a22++) {
		let o22 = i22[a22],
			u22 = s22[a22];
		if (o22 < u22) return -1;
		if (o22 > u22) return 1;
		let l22 = t22.value[o22] ?? null,
			h22 = e52.value[u22] ?? null,
			c22 = r.compare(l22, h22, n22);
		if (0 !== c22) return c22;
	}
	return 0;
}
function th(t22) {
	return {
		type: P.ResponsiveImage,
		value: t22.readJson(),
	};
}
function tc(t22, e52) {
	t22.writeJson(e52.value);
}
function tf(t22, e52) {
	let r22 = JSON.stringify(t22.value),
		n22 = JSON.stringify(e52.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function td(t22) {
	let e52 = t22.readInt8();
	if (0 === e52)
		return {
			type: P.RichText,
			value: t22.readUint32(),
		};
	if (1 === e52)
		return {
			type: P.RichText,
			value: t22.readString(),
		};
	throw Error("Invalid rich text pointer");
}
function tg(t22, e52) {
	if (N(e52.value)) {
		t22.writeInt8(0), t22.writeUint32(e52.value);
		return;
	}
	if (x(e52.value)) {
		t22.writeInt8(1), t22.writeString(e52.value);
		return;
	}
	throw Error("Invalid rich text pointer");
}
function tv(t22, e52) {
	let r22 = t22.value,
		n22 = e52.value;
	if ((N(r22) && N(n22)) || (x(r22) && x(n22)))
		return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
	throw Error("Invalid rich text pointer");
}
function tp(t22) {
	return {
		type: P.String,
		value: t22.readString(),
	};
}
function ty(t22, e52) {
	t22.writeString(e52.value);
}
function tm(t22, e52, r22) {
	let n22 = t22.value,
		i22 = e52.value;
	return (0 === r22.type &&
		((n22 = t22.value.toLowerCase()), (i22 = e52.value.toLowerCase())),
	n22 < i22)
		? -1
		: n22 > i22
			? 1
			: 0;
}
function tw(t22) {
	return {
		type: P.VectorSetItem,
		value: t22.readUint32(),
	};
}
function tI(t22, e52) {
	t22.writeUint32(e52.value);
}
function tb(t22, e52) {
	let r22 = t22.value,
		n22 = e52.value;
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
((t22) => {
	(t22.read = function (t32) {
		let e52 = t32.readUint8();
		switch (e52) {
			case 0:
				return null;
			case 1:
				return q(t32);
			case 2:
				return D(t32);
			case 3:
				return V(t32);
			case 4:
				return z(t32);
			case 5:
				return H(t32);
			case 6:
				return Y(t32);
			case 7:
				return te(t32);
			case 8:
				return ti(t32);
			case 9:
				return to(t32);
			case 10:
				return th(t32);
			case 11:
				return td(t32);
			case 12:
				return tp(t32);
			case 13:
				return tw(t32);
			default:
				b(e52);
		}
	}),
		(t22.write = function (t32, e52) {
			let r22 = R(e52);
			if ((t32.writeUint8(r22), !A(e52)))
				switch (e52.type) {
					case P.Array:
						return _(t32, e52);
					case P.Boolean:
						return C(t32, e52);
					case P.Color:
						return W(t32, e52);
					case P.Date:
						return G(t32, e52);
					case P.Enum:
						return X(t32, e52);
					case P.File:
						return Z(t32, e52);
					case P.Link:
						return tr(t32, e52);
					case P.Number:
						return ts(t32, e52);
					case P.Object:
						return tu(t32, e52);
					case P.ResponsiveImage:
						return tc(t32, e52);
					case P.RichText:
						return tg(t32, e52);
					case P.VectorSetItem:
						return tI(t32, e52);
					case P.String:
						return ty(t32, e52);
					default:
						b(e52);
				}
		}),
		(t22.compare = function (t32, e52, r22) {
			let n22 = R(t32),
				i22 = R(e52);
			if (n22 < i22) return -1;
			if (n22 > i22) return 1;
			if (A(t32) || A(e52)) return 0;
			switch (t32.type) {
				case P.Array:
					return I(e52.type === P.Array), j(t32, e52, r22);
				case P.Boolean:
					return I(e52.type === P.Boolean), J(t32, e52);
				case P.Color:
					return I(e52.type === P.Color), $(t32, e52);
				case P.Date:
					return I(e52.type === P.Date), K(t32, e52);
				case P.Enum:
					return I(e52.type === P.Enum), Q(t32, e52);
				case P.File:
					return I(e52.type === P.File), tt(t32, e52);
				case P.Link:
					return I(e52.type === P.Link), tn(t32, e52);
				case P.Number:
					return I(e52.type === P.Number), ta(t32, e52);
				case P.Object:
					return I(e52.type === P.Object), tl(t32, e52, r22);
				case P.ResponsiveImage:
					return I(e52.type === P.ResponsiveImage), tf(t32, e52);
				case P.RichText:
					return I(e52.type === P.RichText), tv(t32, e52);
				case P.VectorSetItem:
					return I(e52.type === P.VectorSetItem), tb(t32, e52);
				case P.String:
					return I(e52.type === P.String), tm(t32, e52, r22);
				default:
					b(t32);
			}
		});
})(r || (r = {}));
var tU = class e4 {
	sortEntries() {
		this.entries.sort((t22, e52) => {
			for (let n22 = 0; n22 < this.fieldNames.length; n22++) {
				let i22 = t22.values[n22],
					s22 = e52.values[n22],
					a22 = r.compare(i22, s22, this.options.collation);
				if (0 !== a22) return a22;
			}
			return t22.pointer.compare(e52.pointer);
		});
	}
	static async deserialize(t22, n22) {
		let i22 = new v(t22),
			s22 = i22.readJson(),
			a22 = i22.readUint8(),
			o22 = [];
		for (let t32 = 0; t32 < a22; t32++) {
			let t4 = i22.readString();
			o22.push(t4);
		}
		let u22 = new e4(o22, {
				collation: s22,
			}),
			l22 = i22.readUint32(),
			h22 = () => {
				let t32 = [];
				for (let e62 = 0; e62 < a22; e62++) {
					let e7 = r.read(i22);
					t32.push(e7);
				}
				let e52 = O.read(i22);
				u22.entries.push({
					values: t32,
					pointer: e52,
				});
			};
		for (let t32 = 0; t32 < l22; t32++) {
			let t4 = n22?.();
			t4 && (await t4), h22();
		}
		return u22;
	}
	serialize() {
		let t22 = new F();
		for (let e52 of (t22.writeJson(this.options.collation),
		t22.writeUint8(this.fieldNames.length),
		this.fieldNames))
			t22.writeString(e52);
		for (let e52 of (this.sortEntries(),
		t22.writeUint32(this.entries.length),
		this.entries)) {
			let { values: n22, pointer: i22 } = e52;
			for (let e62 of n22) r.write(t22, e62);
			i22.write(t22);
		}
		return t22.subarray();
	}
	addItem(t22, e52) {
		let r22 = this.fieldNames.map((e62) => t22.getField(e62) ?? null);
		this.entries.push({
			values: r22,
			pointer: e52,
		});
	}
	constructor(e52, r22) {
		t(this, "fieldNames", void 0),
			t(this, "options", void 0),
			t(this, "entries", []),
			(this.fieldNames = e52),
			(this.options = r22);
	}
};
var tS = 3;
var tk = 250;
var tL = [
	408,
	// Request Timeout
	429,
	// Too Many Requests
	500,
	// Internal Server Error
	502,
	// Bad Gateway
	503,
	// Service Unavailable
	504,
];
var tB = async (t22, e52) => {
	let r22 = 0;
	for (;;) {
		try {
			let n22 = await fetch(t22, e52);
			if (!tL.includes(n22.status) || ++r22 > tS) return n22;
		} catch (t32) {
			if (e52?.signal?.aborted || ++r22 > tS) throw t32;
		}
		await tE(r22);
	}
};
async function tE(t22) {
	let e52 = Math.floor(tk * (Math.random() + 1) * 2 ** (t22 - 1));
	await new Promise((t32) => {
		setTimeout(t32, e52);
	});
}
async function tT(t22, e52) {
	let r22 = tx(e52),
		n22 = [],
		i22 = 0;
	for (let t32 of r22)
		n22.push(`${t32.from}-${t32.to - 1}`), (i22 += t32.to - t32.from);
	let s22 = new URL(t22),
		a22 = n22.join(",");
	s22.searchParams.set("range", a22);
	let o22 = await tB(s22);
	if (200 !== o22.status)
		throw Error(`Request failed: ${o22.status} ${o22.statusText}`);
	let u22 = await o22.arrayBuffer(),
		l22 = new Uint8Array(u22);
	if (l22.length !== i22)
		throw Error("Request failed: Unexpected response length");
	let h22 = new tM(),
		c22 = 0;
	for (let t32 of r22) {
		let e62 = t32.to - t32.from,
			r3 = c22 + e62,
			n32 = l22.subarray(c22, r3);
		h22.write(t32.from, n32), (c22 = r3);
	}
	return e52.map((t32) => h22.read(t32.from, t32.to - t32.from));
}
var tM = class {
	read(t22, e52) {
		for (let r22 of this.chunks) {
			if (t22 < r22.start) break;
			if (t22 > r22.end) continue;
			if (t22 + e52 > r22.end) break;
			let n22 = t22 - r22.start,
				i22 = n22 + e52;
			return r22.data.slice(n22, i22);
		}
		throw Error("Missing data");
	}
	write(t22, e52) {
		let r22 = t22,
			n22 = r22 + e52.length,
			i22 = 0,
			s22 = this.chunks.length;
		for (; i22 < s22; i22++) {
			let t32 = this.chunks[i22];
			if ((I(t32, "Missing chunk"), !(r22 > t32.end))) {
				if (r22 > t32.start) {
					let n32 = r22 - t32.start,
						i3 = t32.data.subarray(0, n32);
					(e52 = tF(i3, e52)), (r22 = t32.start);
				}
				break;
			}
		}
		for (; s22 > i22; s22--) {
			let t32 = this.chunks[s22 - 1];
			if ((I(t32, "Missing chunk"), !(n22 < t32.start))) {
				if (n22 < t32.end) {
					let r3 = n22 - t32.start,
						i3 = t32.data.subarray(r3);
					(e52 = tF(e52, i3)), (n22 = t32.end);
				}
				break;
			}
		}
		let a22 = {
				start: r22,
				end: n22,
				data: e52,
			},
			o22 = s22 - i22;
		this.chunks.splice(i22, o22, a22);
	}
	constructor() {
		t(this, "chunks", []);
	}
};
function tF(t22, e52) {
	let r22 = t22.length + e52.length,
		n22 = new Uint8Array(r22);
	return n22.set(t22, 0), n22.set(e52, t22.length), n22;
}
function tx(t22) {
	I(t22.length > 0, "Must have at least one range");
	let e52 = [...t22].sort((t32, e62) => t32.from - e62.from),
		r22 = [];
	for (let t32 of e52) {
		let e62 = r22.length - 1,
			n22 = r22[e62];
		n22 && t32.from <= n22.to
			? (r22[e62] = {
					from: n22.from,
					to: Math.max(n22.to, t32.to),
				})
			: r22.push(t32);
	}
	return r22;
}
var tN = class {
	async loadModel() {
		let [t22] = await tT(this.options.url, [this.options.range]);
		return I(t22, "Failed to load model"), tU.deserialize(t22);
	}
	async getModel() {
		return (
			(this.modelPromise ??= this.loadModel()),
			(this.model ??= await this.modelPromise),
			this.model
		);
	}
	async lookupItems(t22) {
		I(t22.length === this.fields.length, "Invalid query length");
		let e52 = await this.getModel(),
			r22 = t22.reduce(
				(t32, e62, r3) =>
					t32.flatMap((t4) => {
						switch (e62.type) {
							case "All":
								return [t4];
							case "Equals":
								return this.queryEquals(t4, e62, r3);
							case "NotEquals":
								return this.queryNotEquals(t4, e62, r3);
							case "LessThan":
								return this.queryLessThan(t4, e62, r3);
							case "GreaterThan":
								return this.queryGreaterThan(t4, e62, r3);
							case "Contains":
								return this.queryContains(t4, e62, r3);
							case "StartsWith":
								return this.queryStartsWith(t4, e62, r3);
							case "EndsWith":
								return this.queryEndsWith(t4, e62, r3);
							default:
								b(e62);
						}
					}),
				[e52.entries],
			),
			n22 = [];
		for (let t32 of r22)
			for (let e62 of t32) {
				let t4 = {};
				for (let r3 = 0; r3 < this.options.fieldNames.length; r3++) {
					let n32 = this.options.fieldNames[r3],
						i22 = e62.values[r3];
					t4[n32] = i22;
				}
				n22.push({
					pointer: e62.pointer.toString(),
					data: t4,
				});
			}
		return n22;
	}
	queryEquals(t22, e52, r22) {
		let n22 = this.getLeftMost(t22, r22, e52.value),
			i22 = this.getRightMost(t22, r22, e52.value),
			s22 = t22.slice(n22, i22 + 1);
		return s22.length > 0 ? [s22] : [];
	}
	queryNotEquals(t22, e52, r22) {
		let n22 = this.getLeftMost(t22, r22, e52.value),
			i22 = this.getRightMost(t22, r22, e52.value),
			s22 = [],
			a22 = t22.slice(0, n22);
		a22.length > 0 && s22.push(a22);
		let o22 = t22.slice(i22 + 1);
		return o22.length > 0 && s22.push(o22), s22;
	}
	queryLessThan(t22, e52, r22) {
		let n22 = this.getRightMost(t22, r22, null);
		if (((t22 = t22.slice(n22 + 1)), e52.inclusive)) {
			let n32 = this.getRightMost(t22, r22, e52.value),
				i3 = t22.slice(0, n32 + 1);
			return i3.length > 0 ? [i3] : [];
		}
		let i22 = this.getLeftMost(t22, r22, e52.value),
			s22 = t22.slice(0, i22);
		return s22.length > 0 ? [s22] : [];
	}
	queryGreaterThan(t22, e52, r22) {
		let n22 = this.getRightMost(t22, r22, null);
		if (((t22 = t22.slice(n22 + 1)), e52.inclusive)) {
			let n32 = this.getLeftMost(t22, r22, e52.value),
				i3 = t22.slice(n32);
			return i3.length > 0 ? [i3] : [];
		}
		let i22 = this.getRightMost(t22, r22, e52.value),
			s22 = t22.slice(i22 + 1);
		return s22.length > 0 ? [s22] : [];
	}
	queryContains(t22, e52, r22) {
		return this.findItems(t22, r22, (t32) => {
			if (t32?.type !== y.String || e52.value?.type !== y.String) return false;
			let r3 = t32.value,
				n22 = e52.value.value;
			return (
				0 === this.collation.type &&
					((r3 = r3.toLowerCase()), (n22 = n22.toLowerCase())),
				r3.includes(n22)
			);
		});
	}
	queryStartsWith(t22, e52, r22) {
		return this.findItems(t22, r22, (t32) => {
			if (t32?.type !== y.String || e52.value?.type !== y.String) return false;
			let r3 = t32.value,
				n22 = e52.value.value;
			return (
				0 === this.collation.type &&
					((r3 = r3.toLowerCase()), (n22 = n22.toLowerCase())),
				r3.startsWith(n22)
			);
		});
	}
	queryEndsWith(t22, e52, r22) {
		return this.findItems(t22, r22, (t32) => {
			if (t32?.type !== y.String || e52.value?.type !== y.String) return false;
			let r3 = t32.value,
				n22 = e52.value.value;
			return (
				0 === this.collation.type &&
					((r3 = r3.toLowerCase()), (n22 = n22.toLowerCase())),
				r3.endsWith(n22)
			);
		});
	}
	/**
	 * Returns the index of the left most entry that is equal to the target.
	 *
	 * ```text
	 *   Left most
	 *       ↓
	 * ┌───┬───┬───┬───┬───┬───┐
	 * │ 1 │ 2 │ 2 │ 2 │ 2 │ 3 │
	 * └───┴───┴───┴───┴───┴───┘
	 * ```
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param target The target value to search for.
	 * @returns The index of the left most entry that is equal to the target.
	 */
	getLeftMost(t22, e52, n22) {
		let i22 = 0,
			s22 = t22.length;
		for (; i22 < s22; ) {
			let a22 = (i22 + s22) >> 1,
				o22 = t22[a22],
				u22 = o22.values[e52];
			0 > r.compare(u22, n22, this.collation) ? (i22 = a22 + 1) : (s22 = a22);
		}
		return i22;
	}
	/**
	 * Returns the index of the right most entry that is equal to the target.
	 *
	 * ```text
	 *              Right most
	 *                   ↓
	 * ┌───┬───┬───┬───┬───┬───┐
	 * │ 1 │ 2 │ 2 │ 2 │ 2 │ 3 │
	 * └───┴───┴───┴───┴───┴───┘
	 * ```
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param target The target value to search for.
	 * @returns The index of the right most entry that is equal to the target.
	 */
	getRightMost(t22, e52, n22) {
		let i22 = 0,
			s22 = t22.length;
		for (; i22 < s22; ) {
			let a22 = (i22 + s22) >> 1,
				o22 = t22[a22],
				u22 = o22.values[e52];
			r.compare(u22, n22, this.collation) > 0 ? (s22 = a22) : (i22 = a22 + 1);
		}
		return s22 - 1;
	}
	/**
	 * Finds all items that are matching the predicate and groups adjacent items together.
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param predicate The predicate to match the values against.
	 * @returns An array of chunks that match the predicate.
	 */
	findItems(t22, e52, r22) {
		let n22 = [],
			i22 = 0;
		for (let s22 = 0; s22 < t22.length; s22++) {
			let a22 = t22[s22],
				o22 = a22.values[e52],
				u22 = r22(o22);
			if (!u22) {
				if (i22 < s22) {
					let e62 = t22.slice(i22, s22);
					n22.push(e62);
				}
				i22 = s22 + 1;
			}
		}
		if (i22 < t22.length) {
			let e62 = t22.slice(i22);
			n22.push(e62);
		}
		return n22;
	}
	constructor(e52) {
		t(this, "options", void 0),
			t(this, "schema", void 0),
			t(this, "fields", void 0),
			t(this, "supportedLookupTypes", [
				"All",
				"Equals",
				"NotEquals",
				"LessThan",
				"GreaterThan",
				"Contains",
				"StartsWith",
				"EndsWith",
				/* EndsWith */
			]),
			t(this, "modelPromise", void 0),
			t(this, "model", void 0),
			t(this, "collation", void 0),
			(this.options = e52);
		let r22 = {},
			n22 = [];
		for (let t22 of this.options.fieldNames) {
			let e62 = this.options.collectionSchema[t22];
			I(e62, "Missing definition for field", t22),
				(r22[t22] = e62),
				n22.push({
					type: "Identifier",
					name: t22,
				});
		}
		(this.schema = r22),
			(this.fields = n22),
			(this.collation = this.options.collation);
	}
};
function tA(t22) {
	let e52 = {},
		n22 = t22.readUint16();
	for (let i22 = 0; i22 < n22; i22++) {
		let n32 = t22.readString();
		e52[n32] = r.read(t22);
	}
	return e52;
}
var tO = class {
	scanItems() {
		return (
			(this.itemsPromise ??= tB(this.url).then(async (t22) => {
				if (!t22.ok)
					throw Error(`Request failed: ${t22.status} ${t22.statusText}`);
				let e52 = await t22.arrayBuffer(),
					r22 = new Uint8Array(e52),
					n22 = new v(r22),
					i22 = [],
					s22 = n22.readUint32();
				for (let t32 = 0; t32 < s22; t32++) {
					let t4 = n22.getOffset(),
						e62 = tA(n22),
						r3 = n22.getOffset() - t4,
						s32 = new O(this.id, t4, r3),
						a22 = s32.toString(),
						o22 = {
							pointer: a22,
							data: e62,
						};
					this.itemLoader.prime(a22, o22), i22.push(o22);
				}
				return i22;
			})),
			this.itemsPromise
		);
	}
	resolveItem(t22) {
		return this.itemLoader.load(t22);
	}
	constructor(e52, r22) {
		t(this, "id", void 0),
			t(this, "url", void 0),
			t(this, "itemsPromise", void 0),
			t(
				this,
				"itemLoader",
				new d.default(
					async (t22) => {
						let e62 = t22.map((t32) => {
								let e7 = O.fromString(t32);
								return {
									from: e7.offset,
									to: e7.offset + e7.length,
								};
							}),
							r3 = await tT(this.url, e62);
						return r3.map((e7, r4) => {
							let n22 = new v(e7),
								i22 = tA(n22),
								s22 = t22[r4];
							return (
								I(s22, "Missing pointer"),
								{
									pointer: s22,
									data: i22,
								}
							);
						});
					},
					{
						maxBatchSize: 250,
					},
				),
			),
			(this.id = e52),
			(this.url = r22);
	}
};
var tP = class {
	async scanItems() {
		let t22 = await Promise.all(
			this.chunks.map(async (t32) => t32.scanItems()),
		);
		return t22.flat();
	}
	resolveItems(t22) {
		return Promise.all(
			t22.map((t32) => {
				let e52 = O.fromString(t32),
					r22 = this.chunks[e52.chunkId];
				return I(r22, "Missing chunk"), r22.resolveItem(t32);
			}),
		);
	}
	compareItems(t22, e52) {
		let r22 = O.fromString(t22.pointer),
			n22 = O.fromString(e52.pointer);
		return r22.compare(n22);
	}
	compareValues(t22, e52, n22) {
		return r.compare(t22, e52, n22);
	}
	constructor(e52) {
		t(this, "options", void 0),
			t(this, "id", void 0),
			t(this, "schema", void 0),
			t(this, "indexes", void 0),
			t(this, "resolveRichText", void 0),
			t(this, "resolveVectorSetItem", void 0),
			t(this, "chunks", void 0),
			(this.options = e52),
			(this.chunks = this.options.chunks.map((t22, e62) => new tO(e62, t22))),
			(this.schema = e52.schema),
			(this.indexes = e52.indexes),
			(this.resolveRichText = e52.resolveRichText),
			(this.resolveVectorSetItem = e52.resolveVectorSetItem),
			(this.id = e52.id);
	}
};

// /:https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF-1.js
import { jsx as e5 } from "react/jsx-runtime";
import {
	AutoBreakpointVariant as t2,
	ComponentPresetsConsumer as r2,
	Link as n2,
	motion as o2,
} from "unframer";
import { isValidElement as i2 } from "react";
import { Fragment as p2, createElement as s2 } from "react";
var __unframerWindow2 = typeof window !== "undefined" ? window : void 0;
var a2;
var l2 = "undefined" != typeof __unframerWindow2;
var f2 = l2 && "function" == typeof __unframerWindow2.requestIdleCallback;
var u2 = "preload";
function c2(e22) {
	return (
		"object" == typeof e22 &&
		null !== e22 &&
		!(/* @__PURE__ */ i2(e22)) &&
		u2 in e22
	);
}
function m2(e22, ...t22) {
	if (!e22)
		throw Error(
			"Assertion Error" + (t22.length > 0 ? ": " + t22.join(" ") : ""),
		);
}
var d2 =
	(((a2 = d2 || {})[(a2.Fragment = 1)] = "Fragment"),
	(a2[(a2.Link = 2)] = "Link"),
	(a2[(a2.Module = 3)] = "Module"),
	(a2[(a2.Tag = 4)] = "Tag"),
	(a2[(a2.Text = 5)] = "Text"),
	a2);
function g2(i22) {
	let a22 = /* @__PURE__ */ new Map();
	return (l22) => {
		let f22 = a22.get(l22);
		if (f22) return f22;
		let u22 = JSON.parse(l22),
			d22 = (function a3(l32) {
				switch (l32[0]) {
					case 1: {
						let [, ...e22] = l32,
							t22 = e22.map(a3);
						return s2(p2, void 0, ...t22);
					}
					case 2: {
						let [, e22, ...t22] = l32,
							r22 = t22.map(a3);
						return s2(n2, e22, ...r22);
					}
					case 3: {
						let [, n22, o22, f32, u32] = l32;
						for (let e22 of f32) {
							let t22 = o22[e22];
							t22 && (o22[e22] = a3(t22));
						}
						for (let e22 of u32) {
							let t22 = o22[e22];
							if ("string" != typeof t22) continue;
							let r22 = i22[t22];
							r22 && (c2(r22) && r22.preload(), (o22[e22] = r22));
						}
						let p22 = i22[n22];
						return (
							m2(p22, "Module not found"),
							c2(p22) && p22.preload(),
							e5(r2, {
								suppressHydrationWarning: true,
								componentIdentifier: n22,
								children: (r22) =>
									e5(t2, {
										suppressHydrationWarning: true,
										component: p22,
										props: {
											...r22,
											...o22,
										},
									}),
							})
						);
					}
					case 4: {
						let [, e22, t22, ...r22] = l32,
							n22 = r22.map(a3);
						if ("a" === e22) return <o2.a />;
						return s2(e22, t22, ...n22);
					}
					case 5: {
						let [, e22] = l32;
						return e22;
					}
				}
			})(u22);
		return a22.set(l22, d22), d22;
	};
}

// /:https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js
var o3 = {
	bnzR2jL1L: {
		isNullable: true,
		type: l3.String,
	},
	createdAt: {
		isNullable: true,
		type: l3.Date,
	},
	dgCkic3lo: {
		isNullable: true,
		type: l3.Boolean,
	},
	E8SjEwsDU: {
		isNullable: true,
		type: l3.Number,
	},
	Ee4yihyME: {
		isNullable: true,
		type: l3.RichText,
	},
	HIPt8rkC0: {
		isNullable: true,
		type: l3.File,
	},
	id: {
		isNullable: false,
		type: l3.String,
	},
	JIoe_7ht2: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
	LzCS9tcWa: {
		definition: {
			definitions: {
				id: {
					isNullable: false,
					type: l3.String,
				},
				VlmCmJPz5: {
					isNullable: true,
					type: l3.ResponsiveImage,
				},
			},
			isNullable: true,
			type: l3.Object,
		},
		isNullable: true,
		type: l3.Array,
	},
	nextItemId: {
		isNullable: true,
		type: l3.String,
	},
	previousItemId: {
		isNullable: true,
		type: l3.String,
	},
	R0waOda6H: {
		isNullable: true,
		type: l3.String,
	},
	R1CPTOGfe: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
	U9uBaRGdH: {
		isNullable: true,
		type: l3.String,
	},
	updatedAt: {
		isNullable: true,
		type: l3.Date,
	},
	vIl0Q5RCV: {
		isNullable: true,
		type: l3.Enum,
	},
	zMw_Vkbtn: {
		isNullable: true,
		type: l3.String,
	},
	ZTXUBvNyP: {
		isNullable: true,
		type: l3.String,
	},
};
var m3 = ["id"];
var n3 = {
	type: 1,
};
var c3 = ["previousItemId"];
var d3 = ["nextItemId"];
var u3 = ["id", "bnzR2jL1L"];
var s3 = ["bnzR2jL1L", "id"];
var f3 = {
	type: 0,
};
var p3 = ["E8SjEwsDU"];
var y2 = ["dgCkic3lo"];
var w2 = ["R0waOda6H"];
var h2 = ["U9uBaRGdH"];
var R2 = ["zMw_Vkbtn"];
var g3 = ["ZTXUBvNyP"];
var N2 = ["Ee4yihyME"];
var I2 = ["LzCS9tcWa"];
var L2 = ["bnzR2jL1L"];
var z2 = ["vIl0Q5RCV"];
var b2 = ["R1CPTOGfe"];
var S2 = ["JIoe_7ht2"];
var T2 = ["HIPt8rkC0"];
var U2 = [];
var x2 = (e22) => {
	let l22 = U2[e22];
	if (l22) return l22().then((e32) => e32.default);
};
var V2 = {};
var X2 = g2(V2);
var C2 = new t3();
var F2 = {
	collectionByLocaleId: {
		default: new tP({
			chunks: [
				new URL(
					"./Td5JaKzXF-chunk-default-0.framercms",
					"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
				).href.replace("/modules/", "/cms/"),
			],
			id: "49e003de-3bca-4a0f-82d3-9f04dff47432default",
			indexes: [
				new tN({
					collation: n3,
					collectionSchema: o3,
					fieldNames: m3,
					range: {
						from: 0,
						to: 241,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: n3,
					collectionSchema: o3,
					fieldNames: c3,
					range: {
						from: 241,
						to: 481,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: n3,
					collectionSchema: o3,
					fieldNames: d3,
					range: {
						from: 481,
						to: 717,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: n3,
					collectionSchema: o3,
					fieldNames: u3,
					range: {
						from: 717,
						to: 1073,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: s3,
					range: {
						from: 1073,
						to: 1429,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: p3,
					range: {
						from: 1429,
						to: 1632,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: y2,
					range: {
						from: 1632,
						to: 1772,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: w2,
					range: {
						from: 1772,
						to: 2037,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: h2,
					range: {
						from: 2037,
						to: 2400,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: R2,
					range: {
						from: 2400,
						to: 2627,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: g3,
					range: {
						from: 2627,
						to: 2830,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: N2,
					range: {
						from: 2830,
						to: 4588,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: I2,
					range: {
						from: 4588,
						to: 22943,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: L2,
					range: {
						from: 22943,
						to: 23167,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: z2,
					range: {
						from: 23167,
						to: 23415,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: b2,
					range: {
						from: 23415,
						to: 28883,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: S2,
					range: {
						from: 28883,
						to: 34222,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: f3,
					collectionSchema: o3,
					fieldNames: T2,
					range: {
						from: 34222,
						to: 34567,
					},
					url: new URL(
						"./Td5JaKzXF-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/ukDpmccTGIaNriIJzyqG/fVIwBwqI9k9TX6KPhjST/Td5JaKzXF.js",
					).href.replace("/modules/", "/cms/"),
				}),
			],
			resolveRichText: X2,
			resolveVectorSetItem: x2,
			schema: o3,
		}),
	},
	displayName: "Work Detail",
	id: "49e003de-3bca-4a0f-82d3-9f04dff47432",
};
var stdin_default4 = F2;
e6(F2, {
	E8SjEwsDU: {
		defaultValue: 0,
		displayStepper: true,
		title: "Count",
		type: l3.Number,
	},
	dgCkic3lo: {
		defaultValue: true,
		title: "Featured",
		type: l3.Boolean,
	},
	R0waOda6H: {
		defaultValue: "",
		title: "Project",
		type: l3.String,
	},
	U9uBaRGdH: {
		defaultValue: "",
		title: "Role",
		type: l3.String,
	},
	zMw_Vkbtn: {
		defaultValue: "",
		title: "Brand",
		type: l3.String,
	},
	ZTXUBvNyP: {
		defaultValue: "2025",
		title: "Year",
		type: l3.String,
	},
	Ee4yihyME: {
		defaultValue: "",
		title: "Info",
		type: l3.RichText,
	},
	LzCS9tcWa: {
		__vekterDefault: [],
		control: {
			controls: {
				VlmCmJPz5: {
					title: "Image",
					type: "responsiveimage",
				},
			},
			type: "object",
		},
		title: "Gallery",
		type: l3.Array,
	},
	bnzR2jL1L: {
		preventLocalization: false,
		title: "Slug",
		type: l3.String,
	},
	vIl0Q5RCV: {
		defaultValue: "Xa6VbyBnz",
		options: ["Yh0eieZwv", "Xa6VbyBnz", "dwiVZR6C5", "BEa52GoOY", "tZGI2QhUD"],
		optionTitles: ["4:5", "1:1", "4:3", "3:2", "16:9"],
		title: "Aspect Ratio 1",
		type: l3.Enum,
	},
	R1CPTOGfe: {
		title: "Image 1",
		type: l3.ResponsiveImage,
	},
	JIoe_7ht2: {
		title: "Image 2",
		type: l3.ResponsiveImage,
	},
	HIPt8rkC0: {
		allowedFileTypes: ["mp4"],
		title: "Video",
		type: l3.File,
	},
	createdAt: {
		title: "Created",
		type: l3.Date,
	},
	updatedAt: {
		title: "Updated",
		type: l3.Date,
	},
	previousItemId: {
		dataIdentifier: "local-module:collection/Td5JaKzXF:default",
		title: "Previous",
		type: l3.CollectionReference,
	},
	nextItemId: {
		dataIdentifier: "local-module:collection/Td5JaKzXF:default",
		title: "Next",
		type: l3.CollectionReference,
	},
});

// /:https://framerusercontent.com/modules/njWZzecLs03xuhZxMZYH/wHJZeY1UvD9aB3mBrky3/yKjC3yof7.js
var ViewModeFonts = getFonts(stdin_default3);
var WorkCardFonts = getFonts(stdin_default2);
var AspectRatioFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = [
	"ug9REYHlX",
	"mFc27WGKx",
	"OYjKmZhpH",
	"R7PQRth7w",
	"yvBw2d9OL",
];
var serializationHash = "framer-SPD9x";
var variantClassNames = {
	mFc27WGKx: "framer-v-1nypmqo",
	OYjKmZhpH: "framer-v-i6t2c3",
	R7PQRth7w: "framer-v-2sq3de",
	ug9REYHlX: "framer-v-m6rs5a",
	yvBw2d9OL: "framer-v-7zif55",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.5,
	type: "spring",
};
var convertFromEnum = (value, activeLocale) => {
	switch (value) {
		case "Xa6VbyBnz":
			return "C75SQeAXS";
		case "Yh0eieZwv":
			return "pU1s_A_4A";
		case "dwiVZR6C5":
			return "sip9vn1jk";
		case "BEa52GoOY":
			return "PbPK45whq";
		case "tZGI2QhUD":
			return "iLGiHRb8_";
		default:
			return "C75SQeAXS";
	}
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var prefix = (value, prefix2) => {
	if (typeof value === "string" && typeof prefix2 === "string") {
		return prefix2 + value;
	} else if (typeof value === "string") {
		return value;
	} else if (typeof prefix2 === "string") {
		return prefix2;
	}
	return "";
};
var suffix = (value, suffix2) => {
	if (typeof value === "string" && typeof suffix2 === "string") {
		return value + suffix2;
	} else if (typeof value === "string") {
		return value;
	} else if (typeof suffix2 === "string") {
		return suffix2;
	}
	return "";
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	bounce: 0,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var convertFromEnum1 = (value, activeLocale) => {
	switch (value) {
		case "Xa6VbyBnz":
			return "C75SQeAXS";
		case "Yh0eieZwv":
			return "pU1s_A_4A";
		case "dwiVZR6C5":
			return "sip9vn1jk";
		case "BEa52GoOY":
			return "PbPK45whq";
		case "tZGI2QhUD":
			return "iLGiHRb8_";
		default:
			return "pU1s_A_4A";
	}
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Grid 2": "mFc27WGKx",
	"Grid 3": "ug9REYHlX",
	"Phone-Img": "R7PQRth7w",
	"Phone-List": "yvBw2d9OL",
	List: "OYjKmZhpH",
};
var getProps = ({ cursor, height, id, width, ...props }) => {
	return {
		...props,
		SrntXGxaS: cursor ?? props.SrntXGxaS,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ug9REYHlX",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		SrntXGxaS,
		vIl0Q5RCVywIQI30KC,
		R1CPTOGfeywIQI30KC,
		JIoe_7ht2ywIQI30KC,
		HIPt8rkC0ywIQI30KC,
		R0waOda6HywIQI30KC,
		U9uBaRGdHywIQI30KC,
		ZTXUBvNyPywIQI30KC,
		bnzR2jL1LywIQI30KC,
		idywIQI30KC,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ug9REYHlX",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const I1z4Nt7sO1k7d0d7 = activeVariantCallback(async (...args) => {
		setVariant("ug9REYHlX");
	});
	const I1z4Nt7sO1sri06h = activeVariantCallback(async (...args) => {
		setVariant("mFc27WGKx");
	});
	const I1z4Nt7sO12e654q = activeVariantCallback(async (...args) => {
		setVariant("OYjKmZhpH");
	});
	const I1z4Nt7sO166ca3 = activeVariantCallback(async (...args) => {
		setVariant("yvBw2d9OL");
	});
	const I1z4Nt7sOgh2osq = activeVariantCallback(async (...args) => {
		setVariant("R7PQRth7w");
	});
	const uYg69jNBstxyyif = ({ overlay, loadMore }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["R7PQRth7w", "yvBw2d9OL"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (["R7PQRth7w", "yvBw2d9OL"].includes(baseVariant)) return true;
		return false;
	};
	const router = useRouter();
	const dynamicRef = useDynamicRefs();
	const isDisplayed2 = () => {
		if (baseVariant === "OYjKmZhpH") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-m6rs5a",
							className,
							classNames,
						)}
						data-framer-name={"Grid 3"}
						layoutDependency={layoutDependency}
						layoutId={"ug9REYHlX"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								mFc27WGKx: {
									"data-framer-name": "Grid 2",
								},
								OYjKmZhpH: {
									"data-framer-name": "List",
								},
								R7PQRth7w: {
									"data-framer-name": "Phone-Img",
								},
								yvBw2d9OL: {
									"data-framer-name": "Phone-List",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-kcy7uk"}
							data-framer-name={"View"}
							layoutDependency={layoutDependency}
							layoutId={"afuy1gnNE"}
						>
							{isDisplayed() && (
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={22}
									y={(componentViewport?.y || 0) + 16 + 0 + 0}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1oly6xt-container"}
										layoutDependency={layoutDependency}
										layoutId={"Cg2G6zKoN-container"}
										nodeId={"Cg2G6zKoN"}
										rendersWithMotion={true}
										scopeId={"yKjC3yof7"}
									>
										{_jsx(stdin_default3, {
											suppressHydrationWarning: true,
											height: "100%",
											I1z4Nt7sO: I1z4Nt7sO1k7d0d7,
											id: "Cg2G6zKoN",
											layoutId: "Cg2G6zKoN",
											variant: "noWFdaAZ5",
											width: "100%",
											yMmNF43J6: "Grid 3",
											...addPropertyOverrides(
												{
													mFc27WGKx: {
														variant: "SbD0rbeNX",
													},
													OYjKmZhpH: {
														variant: "SbD0rbeNX",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed() && (
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									height={22}
									y={(componentViewport?.y || 0) + 16 + 0 + 0}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1a4p2hv-container"}
										layoutDependency={layoutDependency}
										layoutId={"q7kkpY_Sw-container"}
										nodeId={"q7kkpY_Sw"}
										rendersWithMotion={true}
										scopeId={"yKjC3yof7"}
									>
										{_jsx(stdin_default3, {
											suppressHydrationWarning: true,
											height: "100%",
											I1z4Nt7sO: I1z4Nt7sO1sri06h,
											id: "q7kkpY_Sw",
											layoutId: "q7kkpY_Sw",
											variant: "SbD0rbeNX",
											width: "100%",
											yMmNF43J6: "Grid 2",
											...addPropertyOverrides(
												{
													mFc27WGKx: {
														variant: "noWFdaAZ5",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							<ComponentViewportProvider
								suppressHydrationWarning={true}
								height={22}
								y={(componentViewport?.y || 0) + 16 + 0 + 0}
							>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-e04eu-container"}
									layoutDependency={layoutDependency}
									layoutId={"oZ77qVY7L-container"}
									nodeId={"oZ77qVY7L"}
									rendersWithMotion={true}
									scopeId={"yKjC3yof7"}
								>
									{_jsx(stdin_default3, {
										suppressHydrationWarning: true,
										height: "100%",
										I1z4Nt7sO: I1z4Nt7sO12e654q,
										id: "oZ77qVY7L",
										layoutId: "oZ77qVY7L",
										variant: "SbD0rbeNX",
										width: "100%",
										yMmNF43J6: "List",
										...addPropertyOverrides(
											{
												OYjKmZhpH: {
													variant: "noWFdaAZ5",
												},
												R7PQRth7w: {
													I1z4Nt7sO: I1z4Nt7sO166ca3,
												},
												yvBw2d9OL: {
													variant: "noWFdaAZ5",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							{isDisplayed1() && (
								<ComponentViewportProvider
									suppressHydrationWarning={true}
									{...addPropertyOverrides(
										{
											R7PQRth7w: {
												height: 22,
												y: (componentViewport?.y || 0) + 16 + 0 + 0,
											},
											yvBw2d9OL: {
												height: 22,
												y: (componentViewport?.y || 0) + 16 + 0 + 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										suppressHydrationWarning={true}
										className={"framer-1emo9kg-container"}
										layoutDependency={layoutDependency}
										layoutId={"l34_uScHf-container"}
										nodeId={"l34_uScHf"}
										rendersWithMotion={true}
										scopeId={"yKjC3yof7"}
									>
										{_jsx(stdin_default3, {
											suppressHydrationWarning: true,
											height: "100%",
											id: "l34_uScHf",
											layoutId: "l34_uScHf",
											variant: "SbD0rbeNX",
											width: "100%",
											yMmNF43J6: "Img",
											...addPropertyOverrides(
												{
													R7PQRth7w: {
														variant: "noWFdaAZ5",
													},
													yvBw2d9OL: {
														I1z4Nt7sO: I1z4Nt7sOgh2osq,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.div>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1tmfswv"}
							layoutDependency={layoutDependency}
							layoutId={"ywIQI30KC"}
						>
							<ChildrenCanSuspend suppressHydrationWarning={true}>
								<QueryData
									suppressHydrationWarning={true}
									query={{
										from: {
											alias: "ywIQI30KC",
											data: stdin_default4,
											type: "Collection",
										},
										select: [
											{
												collection: "ywIQI30KC",
												name: "vIl0Q5RCV",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "R1CPTOGfe",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "JIoe_7ht2",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "HIPt8rkC0",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "R0waOda6H",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "U9uBaRGdH",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "ZTXUBvNyP",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "bnzR2jL1L",
												type: "Identifier",
											},
											{
												collection: "ywIQI30KC",
												name: "id",
												type: "Identifier",
											},
										],
									}}
								>
									{(collection, paginationInfo, loadMore) => (
										<_Fragment>
											{collection?.map(
												(
													{
														bnzR2jL1L: bnzR2jL1LywIQI30KC2,
														HIPt8rkC0: HIPt8rkC0ywIQI30KC2,
														id: idywIQI30KC2,
														JIoe_7ht2: JIoe_7ht2ywIQI30KC2,
														R0waOda6H: R0waOda6HywIQI30KC2,
														R1CPTOGfe: R1CPTOGfeywIQI30KC2,
														U9uBaRGdH: U9uBaRGdHywIQI30KC2,
														vIl0Q5RCV: vIl0Q5RCVywIQI30KC2,
														ZTXUBvNyP: ZTXUBvNyPywIQI30KC2,
													},
													index,
												) => {
													R0waOda6HywIQI30KC2 ??= "";
													U9uBaRGdHywIQI30KC2 ??= "";
													ZTXUBvNyPywIQI30KC2 ??= "";
													bnzR2jL1LywIQI30KC2 ??= "";
													return (
														<LayoutGroup
															suppressHydrationWarning={true}
															id={`ywIQI30KC-${idywIQI30KC2}`}
														>
															<PathVariablesContext.Provider
																suppressHydrationWarning={true}
																value={{
																	bnzR2jL1L: bnzR2jL1LywIQI30KC2,
																}}
															>
																<Overlay
																	suppressHydrationWarning={true}
																	blockDocumentScrolling={false}
																	enabled={isDisplayed2()}
																>
																	{(overlay) => (
																		<_Fragment>
																			<ResolveLinks
																				suppressHydrationWarning={true}
																				links={[
																					{
																						href: {
																							pathVariables: {
																								bnzR2jL1L: bnzR2jL1LywIQI30KC2,
																							},
																							webPageId: "c0tWLGzJ6",
																						},
																						implicitPathVariables: void 0,
																					},
																					{
																						href: {
																							pathVariables: {
																								bnzR2jL1L: bnzR2jL1LywIQI30KC2,
																							},
																							webPageId: "c0tWLGzJ6",
																						},
																						implicitPathVariables: void 0,
																					},
																					{
																						href: {
																							pathVariables: {
																								bnzR2jL1L: bnzR2jL1LywIQI30KC2,
																							},
																							webPageId: "c0tWLGzJ6",
																						},
																						implicitPathVariables: void 0,
																					},
																					{
																						href: {
																							pathVariables: {
																								bnzR2jL1L: bnzR2jL1LywIQI30KC2,
																							},
																							webPageId: "c0tWLGzJ6",
																						},
																						implicitPathVariables: void 0,
																					},
																					{
																						href: {
																							pathVariables: {
																								bnzR2jL1L: bnzR2jL1LywIQI30KC2,
																							},
																							webPageId: "c0tWLGzJ6",
																						},
																						implicitPathVariables: void 0,
																					},
																				]}
																			>
																				{(resolvedLinks) => (
																					<ComponentViewportProvider
																						suppressHydrationWarning={true}
																						height={400}
																						width={`max((${componentViewport?.width || "100vw"} - 48px) / 3, 50px)`}
																						y={
																							(componentViewport?.y || 0) +
																							16 +
																							54 +
																							0 +
																							0
																						}
																						{...addPropertyOverrides(
																							{
																								mFc27WGKx: {
																									width: `max((${componentViewport?.width || "100vw"} - 40px) / 2, 50px)`,
																								},
																								OYjKmZhpH: {
																									width: `min(${componentViewport?.width || "100vw"} - 32px, 640px)`,
																								},
																								R7PQRth7w: {
																									width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
																								},
																								yvBw2d9OL: {
																									width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						)}
																					>
																						<SmartComponentScopedContainer
																							suppressHydrationWarning={true}
																							className={
																								"framer-1ucg607-container"
																							}
																							id={`${bnzR2jL1LywIQI30KC2}-${layoutId}-1ucg607`}
																							layoutDependency={
																								layoutDependency
																							}
																							layoutId={"h_X96fpP9-container"}
																							nodeId={"h_X96fpP9"}
																							ref={dynamicRef(
																								`${bnzR2jL1LywIQI30KC2}-${layoutId}-1ucg607`,
																							)}
																							rendersWithMotion={true}
																							scopeId={"yKjC3yof7"}
																						>
																							{_jsx(stdin_default2, {
																								suppressHydrationWarning: true,
																								eXcjQQP8X: convertFromEnum(
																									vIl0Q5RCVywIQI30KC2,
																									activeLocale,
																								),
																								GldoSFqFp:
																									toResponsiveImage(
																										R1CPTOGfeywIQI30KC2,
																									),
																								H7TfhEkie: ZTXUBvNyPywIQI30KC2,
																								height: "100%",
																								id: "h_X96fpP9",
																								layoutId: "h_X96fpP9",
																								n0LrKpBOv:
																									toResponsiveImage(
																										JIoe_7ht2ywIQI30KC2,
																									),
																								RArmZ_R1s: suffix(
																									prefix(
																										R0waOda6HywIQI30KC2,
																										"[ ",
																									),
																									" ]",
																								),
																								style: {
																									width: "100%",
																								},
																								uYg69jNBs: uYg69jNBstxyyif({
																									overlay,
																								}),
																								variant: "oMcQ1DNuC",
																								wBClPsWvK: SrntXGxaS,
																								width: "100%",
																								XjljonNMF: U9uBaRGdHywIQI30KC2,
																								xYtJnpLHG: resolvedLinks[0],
																								ZMCBWuLjx: HIPt8rkC0ywIQI30KC2,
																								...addPropertyOverrides(
																									{
																										mFc27WGKx: {
																											xYtJnpLHG:
																												resolvedLinks[1],
																										},
																										OYjKmZhpH: {
																											style: {
																												maxWidth: "100%",
																												width: "100%",
																											},
																											variant: "nJIHm8KWU",
																											xYtJnpLHG:
																												resolvedLinks[2],
																										},
																										R7PQRth7w: {
																											xYtJnpLHG:
																												resolvedLinks[3],
																										},
																										yvBw2d9OL: {
																											variant: "nJIHm8KWU",
																											xYtJnpLHG:
																												resolvedLinks[4],
																										},
																									},
																									baseVariant,
																									gestureVariant,
																								),
																							})}
																							{isDisplayed2() && (
																								<AnimatePresence
																									suppressHydrationWarning={
																										true
																									}
																								>
																									{overlay.visible && (
																										<Floating
																											suppressHydrationWarning={
																												true
																											}
																											alignment={"center"}
																											anchorRef={dynamicRef(
																												`${bnzR2jL1LywIQI30KC2}-${layoutId}-1ucg607`,
																											)}
																											className={cx(
																												scopingClassNames,
																												classNames,
																											)}
																											collisionDetection={true}
																											collisionDetectionPadding={
																												20
																											}
																											data-framer-portal-id={`${bnzR2jL1LywIQI30KC2}-${layoutId}-1ucg607`}
																											offsetX={0}
																											offsetY={10}
																											onDismiss={overlay.hide}
																											placement={"bottom"}
																											safeArea={true}
																											zIndex={11}
																											{...addPropertyOverrides(
																												{
																													OYjKmZhpH: {
																														offsetY: 0,
																														placement: "right",
																													},
																												},
																												baseVariant,
																												gestureVariant,
																											)}
																										>
																											<MotionDivWithFX
																												suppressHydrationWarning={
																													true
																												}
																												__perspectiveFX={false}
																												__smartComponentFX={
																													true
																												}
																												__targetOpacity={1}
																												animate={animation1}
																												className={
																													"framer-15sozic"
																												}
																												exit={animation}
																												initial={animation2}
																												layoutDependency={
																													layoutDependency
																												}
																												layoutId={"dczYsuyG4"}
																												ref={dynamicRef(
																													`${bnzR2jL1LywIQI30KC2}-${layoutId}-15sozic`,
																												)}
																												role={"dialog"}
																												{...addPropertyOverrides(
																													{
																														OYjKmZhpH: {
																															animate:
																																animation4,
																															exit: animation3,
																															initial:
																																animation5,
																														},
																													},
																													baseVariant,
																													gestureVariant,
																												)}
																											>
																												{isDisplayed2() && (
																													<ComponentViewportProvider
																														suppressHydrationWarning={
																															true
																														}
																														{...addPropertyOverrides(
																															{
																																OYjKmZhpH: {
																																	width:
																																		"320px",
																																},
																															},
																															baseVariant,
																															gestureVariant,
																														)}
																													>
																														<SmartComponentScopedContainer
																															suppressHydrationWarning={
																																true
																															}
																															className={
																																"framer-9sn48d-container"
																															}
																															inComponentSlot={
																																true
																															}
																															layoutDependency={
																																layoutDependency
																															}
																															layoutId={
																																"wZhZ9Csh0-container"
																															}
																															nodeId={
																																"wZhZ9Csh0"
																															}
																															rendersWithMotion={
																																true
																															}
																															scopeId={
																																"yKjC3yof7"
																															}
																														>
																															{_jsx(
																																stdin_default,
																																{
																																	suppressHydrationWarning: true,
																																	height:
																																		"100%",
																																	id: "wZhZ9Csh0",
																																	layoutId:
																																		"wZhZ9Csh0",
																																	style: {
																																		width:
																																			"100%",
																																	},
																																	variant:
																																		"pU1s_A_4A",
																																	width: "100%",
																																	wrFqzdxX4: true,
																																	...addPropertyOverrides(
																																		{
																																			OYjKmZhpH:
																																				{
																																					AQYOlE2Ws:
																																						HIPt8rkC0ywIQI30KC2,
																																					RzspQAp52:
																																						toResponsiveImage(
																																							R1CPTOGfeywIQI30KC2,
																																						),
																																					variant:
																																						convertFromEnum1(
																																							vIl0Q5RCVywIQI30KC2,
																																							activeLocale,
																																						),
																																					wrFqzdxX4:
																																						isSet(
																																							HIPt8rkC0ywIQI30KC2,
																																						),
																																				},
																																		},
																																		baseVariant,
																																		gestureVariant,
																																	),
																																},
																															)}
																														</SmartComponentScopedContainer>
																													</ComponentViewportProvider>
																												)}
																											</MotionDivWithFX>
																										</Floating>
																									)}
																								</AnimatePresence>
																							)}
																						</SmartComponentScopedContainer>
																					</ComponentViewportProvider>
																				)}
																			</ResolveLinks>
																		</_Fragment>
																	)}
																</Overlay>
															</PathVariablesContext.Provider>
														</LayoutGroup>
													);
												},
											)}
										</_Fragment>
									)}
								</QueryData>
							</ChildrenCanSuspend>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SPD9x.framer-19znsj8, .framer-SPD9x .framer-19znsj8 { display: block; }",
	".framer-SPD9x.framer-m6rs5a { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px; position: relative; width: 1200px; }",
	".framer-SPD9x .framer-kcy7uk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-SPD9x .framer-1oly6xt-container, .framer-SPD9x .framer-1a4p2hv-container, .framer-SPD9x .framer-e04eu-container, .framer-SPD9x .framer-1emo9kg-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-SPD9x .framer-1tmfswv { display: grid; flex: none; gap: 8px 8px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(3, minmax(50px, 1fr)); height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-SPD9x .framer-1ucg607-container { align-self: start; flex: none; height: auto; justify-self: center; position: relative; width: 100%; }",
	".framer-SPD9x .framer-15sozic { height: 150px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 200px; }",
	".framer-SPD9x .framer-9sn48d-container { flex: none; height: auto; left: -641px; position: absolute; top: -470px; width: 400px; }",
	".framer-SPD9x.framer-v-1nypmqo .framer-1tmfswv { grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-SPD9x.framer-v-i6t2c3 .framer-1tmfswv { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; justify-content: flex-start; }",
	".framer-SPD9x.framer-v-i6t2c3 .framer-1ucg607-container { align-self: unset; max-width: 640px; }",
	".framer-SPD9x.framer-v-i6t2c3 .framer-15sozic { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: center; padding: 0px; width: min-content; }",
	".framer-SPD9x.framer-v-i6t2c3 .framer-9sn48d-container { left: unset; position: relative; top: unset; width: 320px; }",
	".framer-SPD9x.framer-v-2sq3de.framer-m6rs5a, .framer-SPD9x.framer-v-7zif55.framer-m6rs5a { width: 600px; }",
	".framer-SPD9x.framer-v-2sq3de .framer-e04eu-container, .framer-SPD9x.framer-v-7zif55 .framer-e04eu-container { order: 3; }",
	".framer-SPD9x.framer-v-2sq3de .framer-1emo9kg-container, .framer-SPD9x.framer-v-7zif55 .framer-1emo9kg-container { order: 2; }",
	".framer-SPD9x.framer-v-2sq3de .framer-1tmfswv, .framer-SPD9x.framer-v-7zif55 .framer-1tmfswv { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; }",
	".framer-SPD9x.framer-v-2sq3de .framer-1ucg607-container, .framer-SPD9x.framer-v-7zif55 .framer-1ucg607-container { align-self: unset; }",
];
var FrameryKjC3yof7 = withCSS(Component, css, "framer-SPD9x");
var stdin_default5 = FrameryKjC3yof7;
FrameryKjC3yof7.displayName = "Work View";
FrameryKjC3yof7.defaultProps = {
	height: 1542,
	width: 1200,
};
addPropertyControls(FrameryKjC3yof7, {
	variant: {
		options: ["ug9REYHlX", "mFc27WGKx", "OYjKmZhpH", "R7PQRth7w", "yvBw2d9OL"],
		optionTitles: ["Grid 3", "Grid 2", "List", "Phone-Img", "Phone-List"],
		title: "Variant",
		type: ControlType.Enum,
	},
	SrntXGxaS: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
});
addFonts(
	FrameryKjC3yof7,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ViewModeFonts,
		...WorkCardFonts,
		...AspectRatioFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:work-view
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WorkViewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"9ea48a1aa2eafa92e080e406f68f150ff9542bbabe94796f6ce5d970d4fe98ea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var work_view_default = ComponentWithRoot;
export { work_view_default as default };
